-- Contenu servi depuis Supabase plutôt que figé dans le bundle.
--
-- Corriger une attribution ou ajouter dix citations demandait jusqu'ici une soumission
-- App Store complète, review comprise. La table ci-dessous devient la source de vérité ;
-- `Shared/Content/content.json` reste embarqué et sert de secours au premier lancement et
-- hors ligne (voir `ContentStore.loadQuotes`).
--
-- `context`, `source` et `year` sont nuls partout au départ : ce sont des faits à
-- vérifier un par un, pas quelque chose qui se génère. L'app les affiche quand ils
-- existent et se tait quand ils manquent.

create table if not exists public.quotes (
  id text primary key,
  text text not null,
  author text not null,
  category text not null,
  context text,
  source text,
  year integer,
  updated_at timestamptz not null default now()
);

alter table public.quotes enable row level security;

-- Lecture pour tout compte connecté, écriture pour personne : le contenu se modifie
-- depuis le SQL Editor ou avec `service_role`, jamais depuis l'app.
drop policy if exists "read quotes" on public.quotes;
create policy "read quotes" on public.quotes
  for select
  to authenticated
  using (true);

revoke insert, update, delete on public.quotes from authenticated, anon;

create index if not exists quotes_category_idx on public.quotes (category);

-- Amorçage depuis le contenu embarqué. `on conflict do nothing` : rejouer la migration ne
-- doit jamais écraser une correction faite depuis.

insert into public.quotes (id, text, author, category) values
  ('q-0005', 'Quand vous êtes dans le sens contraire du courant et que vous nagez vite, vous reculez moins que les autres.', 'Bernard Tapie', 'mindset'),
  ('q-0006', 'La réussite, c''est un peu de talent, beaucoup de travail et surtout une passion dévorante.', 'Bernard Tapie', 'mindset'),
  ('q-0007', 'Seul un poisson mort navigue dans le sens du courant.', 'Bernard Arnault', 'mindset'),
  ('q-0008', 'Un bon produit peut durer éternellement.', 'Bernard Arnault', 'mindset'),
  ('q-0009', 'Si vous contrôlez votre distribution, vous contrôlez votre image.', 'Bernard Arnault', 'leadership'),
  ('q-0011', 'La seule façon de faire du bon travail est d''aimer ce que vous faites.', 'Steve Jobs', 'mindset'),
  ('q-0012', 'L''innovation distingue un leader d''un suiveur.', 'Steve Jobs', 'leadership'),
  ('q-0013', 'Votre temps est limité, ne le gaspillez pas en vivant la vie de quelqu''un d''autre.', 'Steve Jobs', 'mindset'),
  ('q-0014', 'Qu''est-ce qu''une entreprise ? C''est simplement une idée qui améliore la vie de quelqu''un d''autre.', 'Richard Branson', 'leadership'),
  ('q-0015', 'Écoutez plus que vous parlez. Personne n''a rien appris en s''entendant parler.', 'Richard Branson', 'leadership'),
  ('q-0016', 'Seul un imbécile ne change jamais d''avis.', 'Richard Branson', 'mindset'),
  ('q-0017', 'L''opportunité se situe à l''endroit où se trouvent les réclamations et les plaintes.', 'Jack Ma', 'mindset'),
  ('q-0019', 'L''échec est simplement l''opportunité de recommencer, cette fois de manière plus pertinente.', 'Henry Ford', 'mindset'),
  ('q-0020', 'Prenez mes idées, j''en aurai d''autres.', 'Coco Chanel', 'mindset'),
  ('q-0021', 'Prudence n''est que l''euphémisme de peur.', 'Jules Renard', 'mindset'),
  ('q-0022', 'La peur bloque la compréhension intelligente de la vie.', 'Jiddu Krishnamurti', 'mindset'),
  ('q-0023', 'J''ai appris que le courage n''est pas l''absence de peur, mais la capacité de la vaincre.', 'Nelson Mandela', 'mindset'),
  ('q-0025', 'Le seul endroit où le succès vient avant le travail, c''est dans le dictionnaire.', 'Vidal Sassoon', 'mindset'),
  ('q-0026', 'Les gagnants trouvent des moyens, les perdants des excuses.', 'Franklin D. Roosevelt', 'mindset'),
  ('q-0028', 'L''audace réussit à ceux qui savent profiter des occasions.', 'Marcel Proust', 'mindset'),
  ('q-0029', 'Un pessimiste voit la difficulté dans chaque opportunité. Un optimiste voit une opportunité dans chaque difficulté.', 'Winston Churchill', 'mindset'),
  ('q-0030', 'Ne cherchez pas d''ascenseur, il n''y en a pas : les entrepreneurs prennent toujours l''escalier !', 'Frédéric Mazzella', 'mindset'),
  ('q-0032', 'Le capitalisme est un pari sur le mouvement : c''est de là que vient le progrès.', 'Alain Minc', 'finance'),
  ('q-0033', 'La victoire appartient à celui qui a la persévérance la plus longue.', 'Napoléon Bonaparte', 'mindset'),
  ('q-0034', 'Toutes les choses semblent réalisables par la volonté et le courage.', 'Napoléon Bonaparte', 'mindset'),
  ('q-0035', 'Se concentrer sur le client rend une entreprise plus résiliente.', 'Jeff Bezos', 'sales'),
  ('q-0037', 'Votre marque est ce que les gens disent de vous lorsque vous n''êtes pas dans la pièce.', 'Jeff Bezos', 'sales'),
  ('q-0038', 'Si vous ne voulez jamais être critiqué, ne faites rien de nouveau.', 'Jeff Bezos', 'mindset'),
  ('q-0039', 'Observez les clients, pas les concurrents.', 'Jeff Bezos', 'sales'),
  ('q-0040', 'Si vous voulez être inventif, vous devez être prêt à échouer.', 'Jeff Bezos', 'mindset'),
  ('q-0041', 'L''échec fait partie intégrante de l''invention.', 'Jeff Bezos', 'mindset'),
  ('q-0042', 'Nous sommes têtus sur la vision. Nous sommes flexibles sur les détails.', 'Jeff Bezos', 'leadership'),
  ('q-0043', 'L''échec est une option. Si les choses n''échouent pas, vous n''innovez pas assez.', 'Elon Musk', 'mindset'),
  ('q-0044', 'La persévérance est très importante. N''abandonnez jamais à moins d''y être obligé.', 'Elon Musk', 'mindset'),
  ('q-0045', 'Beaucoup de choses sont improbables, seules quelques-unes sont impossibles.', 'Elon Musk', 'mindset'),
  ('q-0046', 'Si les règles vous empêchent de progresser, battez-vous pour les changer.', 'Elon Musk', 'mindset'),
  ('q-0047', 'Vous devez être assez motivé pour y arriver. Sinon, vous vous rendrez simplement misérable.', 'Elon Musk', 'mindset'),
  ('q-0048', 'Lorsque quelque chose est suffisamment importante, vous la faites même si les chances ne sont pas en votre faveur.', 'Elon Musk', 'mindset'),
  ('q-0050', 'Se réunir est un début ; rester ensemble est un progrès ; travailler ensemble est la réussite.', 'Henry Ford', 'leadership'),
  ('q-0051', 'Quand tout semble être contre vous, souvenez-vous que l''avion décolle face au vent.', 'Henry Ford', 'mindset'),
  ('q-0052', 'Ce n''est pas l''employeur qui paie les salaires, mais le client.', 'Henry Ford', 'sales'),
  ('q-0053', 'Les deux choses les plus importantes n''apparaissent pas au bilan : sa réputation et ses hommes.', 'Henry Ford', 'leadership'),
  ('q-0054', 'La qualité signifie faire les choses correctement quand personne ne regarde.', 'Henry Ford', 'mindset'),
  ('q-0055', 'Les obstacles sont ces choses effrayantes que vous voyez quand vous détournez les yeux de votre objectif.', 'Henry Ford', 'mindset'),
  ('q-0057', 'Il faut 20 ans pour bâtir une réputation et cinq minutes pour l''anéantir.', 'Warren Buffett', 'finance'),
  ('q-0058', 'Le risque provient de ne pas savoir ce que l''on fait.', 'Warren Buffett', 'finance'),
  ('q-0059', 'Achetez seulement des choses que vous seriez parfaitement heureux de posséder si le marché s''effondrait pendant dix ans.', 'Warren Buffett', 'finance'),
  ('q-0060', 'Notre horizon d''investissement préféré est : pour toujours.', 'Warren Buffett', 'finance'),
  ('q-0061', 'La bourse est un moyen de transférer l''argent des impatients vers les patients.', 'Warren Buffett', 'finance'),
  ('q-0062', 'Le meilleur investissement que vous puissiez faire, c''est de miser sur vos propres capacités.', 'Warren Buffett', 'finance'),
  ('q-0063', 'Tous nos rêves peuvent devenir réalité si nous avons le courage de les poursuivre.', 'Walt Disney', 'mindset'),
  ('q-0065', 'La manière de commencer est d''arrêter de parler et de commencer à faire.', 'Walt Disney', 'mindset'),
  ('q-0068', 'Ce n''est pas votre faute si vous êtes né pauvre. En revanche, si vous mourez pauvre, c''est votre erreur.', 'Bill Gates', 'finance'),
  ('q-0069', 'La patience est un élément clé de la réussite.', 'Bill Gates', 'mindset'),
  ('q-0070', 'Le succès est un mauvais professeur. Il pousse les gens intelligents à croire qu''ils sont infaillibles.', 'Bill Gates', 'mindset'),
  ('q-0071', 'Il ne faut jamais se comparer aux autres. Le faire, c''est s''insulter soi-même.', 'Bill Gates', 'mindset'),
  ('q-0072', 'Pour gagner gros, il faut parfois prendre de gros risques.', 'Bill Gates', 'finance'),
  ('q-0073', 'Célébrer le succès, c''est bien, mais il est plus important de tirer les leçons de l''échec.', 'Bill Gates', 'mindset'),
  ('q-0074', 'Le plus grand risque est de ne prendre aucun risque.', 'Mark Zuckerberg', 'mindset'),
  ('q-0075', 'Si les choses ne se cassent pas, vous ne vous déplacez pas assez vite.', 'Mark Zuckerberg', 'mindset'),
  ('q-0076', 'La chose la plus importante est de garder votre équipe aussi petite que possible.', 'Mark Zuckerberg', 'leadership'),
  ('q-0077', 'Mon objectif n''a jamais été de créer une entreprise, mais de bâtir quelque chose susceptible de changer le monde.', 'Mark Zuckerberg', 'leadership'),
  ('q-0079', 'L''échec est un excellent enseignant et chaque erreur a une leçon à offrir.', 'Oprah Winfrey', 'mindset'),
  ('q-0080', 'Entourez-vous seulement de personnes qui vont vous élever plus haut.', 'Oprah Winfrey', 'mindset'),
  ('q-0081', 'Vous ne devenez pas ce que vous voulez, vous devenez ce que vous croyez.', 'Oprah Winfrey', 'mindset'),
  ('q-0085', 'Celui qui n''a pas d''objectifs ne risque pas de les atteindre.', 'Sun Tzu', 'mindset'),
  ('q-0086', 'Le bon général a gagné la bataille avant de l''engager.', 'Sun Tzu', 'leadership'),
  ('q-0087', 'Un grand dirigeant commande par l''exemple et non par la force.', 'Sun Tzu', 'leadership'),
  ('q-0088', 'Connais l''adversaire et surtout connais-toi toi-même et tu seras invincible.', 'Sun Tzu', 'mindset'),
  ('q-0089', 'Le commencement est beaucoup plus que la moitié de l''objectif.', 'Aristote', 'mindset'),
  ('q-0090', 'C''est par l''expérience que la science et l''art font leur progrès.', 'Aristote', 'mindset'),
  ('q-0092', 'Le courage est la première des qualités humaines car elle garantit toutes les autres.', 'Aristote', 'mindset'),
  ('q-0094', 'Faites le premier pas sur le chemin de la foi. Vous n''avez pas à le parcourir entièrement, juste à faire le premier pas.', 'Martin Luther King', 'mindset'),
  ('q-0095', 'Avoir la foi, c''est monter la première marche, même quand on ne voit pas tout l''escalier.', 'Martin Luther King', 'mindset'),
  ('q-0097', 'Tout ce que tu feras sera dérisoire, mais il est essentiel que tu le fasses.', 'Mahatma Gandhi', 'mindset'),
  ('q-0098', 'Je ne crains pas l''homme qui a pratiqué 10 000 coups une fois, mais celui qui a pratiqué un coup 10 000 fois.', 'Bruce Lee', 'mindset'),
  ('q-0099', 'Connaître ne suffit pas, il faut savoir appliquer. La volonté ne suffit pas, il faut savoir agir.', 'Bruce Lee', 'mindset'),
  ('q-0100', 'Ne crains pas l''échec. Ce n''est pas l''échec, mais le manque d''ambition qui est un crime.', 'Bruce Lee', 'mindset'),
  ('q-0101', 'Il n''y a pas de limites. Il y a seulement des niveaux, et tu ne dois pas en rester là.', 'Bruce Lee', 'mindset'),
  ('q-0102', 'C''est dur d''échouer, mais c''est pire de n''avoir jamais essayé de réussir.', 'Theodore Roosevelt', 'mindset'),
  ('q-0103', 'Le seul homme à ne jamais faire d''erreurs est celui qui ne fait rien.', 'Theodore Roosevelt', 'mindset'),
  ('q-0105', 'Parlez doucement, et tenez un gros bâton, vous irez loin.', 'Theodore Roosevelt', 'leadership'),
  ('q-0106', 'N''ayez pas peur d''échouer. Ayez peur de ne pas essayer.', 'Michael Jordan', 'mindset'),
  ('q-0107', 'Je peux accepter l''échec, tout le monde échoue dans quelque chose. Mais je ne peux pas accepter de ne pas essayer.', 'Michael Jordan', 'mindset'),
  ('q-0108', 'Plus je me prépare, plus j''ai de chance.', 'Michael Jordan', 'mindset'),
  ('q-0110', 'Le talent fait gagner les matches, mais le travail d''équipe et l''intelligence font gagner des tournois.', 'Michael Jordan', 'leadership'),
  ('q-0113', 'Il n''y a qu''une réponse à la défaite, et c''est la victoire.', 'Winston Churchill', 'mindset'),
  ('q-0115', 'Pour s''améliorer, il faut changer. Donc, pour être parfait, il faut avoir changé souvent.', 'Winston Churchill', 'mindset'),
  ('q-0116', 'Celui qui déplace la montagne, c''est celui qui commence à enlever les petites pierres.', 'Confucius', 'mindset'),
  ('q-0117', 'Celui qui ne progresse pas chaque jour, recule chaque jour.', 'Confucius', 'mindset'),
  ('q-0118', 'Un homme est grand non pas parce qu''il n''a pas échoué ; un homme est grand parce que l''échec ne l''a pas arrêté.', 'Confucius', 'mindset'),
  ('q-0120', 'Ne vous souciez pas de n''être pas remarqué ; cherchez plutôt à faire quelque chose de remarquable.', 'Confucius', 'mindset'),
  ('q-0121', 'Exige beaucoup de toi-même et attends peu des autres.', 'Confucius', 'mindset'),
  ('q-0122', 'Dans les affaires, les grandes choses ne sont jamais faites par une seule personne.', 'Steve Jobs', 'leadership'),
  ('q-0123', 'Les gens qui sont assez fous pour penser qu''ils peuvent changer le monde sont ceux qui le font.', 'Steve Jobs', 'mindset'),
  ('q-0124', 'La simplicité est la sophistication ultime.', 'Steve Jobs', 'mindset'),
  ('q-0125', 'Je suis convaincu que la moitié qui sépare les entrepreneurs qui réussissent de ceux qui échouent est purement la persévérance.', 'Steve Jobs', 'mindset'),
  ('q-0126', 'Innover, c''est savoir abandonner des milliers de bonnes idées.', 'Steve Jobs', 'mindset'),
  ('q-0127', 'Cela n''a aucun sens d''embaucher des gens intelligents et de leur dire quoi faire.', 'Steve Jobs', 'leadership'),
  ('q-0129', 'Ne quittez jamais les flux de trésorerie des yeux, car c''est le sang de l''entreprise.', 'Richard Branson', 'finance'),
  ('q-0130', 'La complexité est votre ennemie. N''importe quel imbécile peut compliquer quelque chose.', 'Richard Branson', 'mindset'),
  ('q-0131', 'Les opportunités, c''est comme les autobus, il y en a toujours un autre qui arrive.', 'Richard Branson', 'mindset'),
  ('q-0132', 'Si vous vous occupez de votre personnel, ils s''occuperont de vos clients.', 'Richard Branson', 'sales'),
  ('q-0133', 'Vous devez prendre des risques si vous voulez réussir.', 'Richard Branson', 'mindset'),
  ('q-0134', 'Parfois, la décision la plus risquée que vous puissiez prendre est de ne rien faire.', 'Richard Branson', 'mindset'),
  ('q-0135', 'Lancer une entreprise, c''est résoudre des problèmes avec succès.', 'Richard Branson', 'leadership'),
  ('q-0136', 'Réussir en affaires, c''est avant tout créer des liens.', 'Richard Branson', 'sales'),
  ('q-0137', 'Le bonheur est l''ingrédient secret des entreprises prospères.', 'Richard Branson', 'leadership'),
  ('q-0138', 'Ce qu''on obtient en atteignant nos objectifs n''est pas aussi important que ce que l''on devient en les atteignant.', 'Zig Ziglar', 'mindset'),
  ('q-0139', 'La pire décision de toutes est celle que l''on n''a pas prise.', 'Zig Ziglar', 'mindset'),
  ('q-0140', 'La meilleure arme de persuasion que tu possèdes dans ton arsenal est l''intégrité.', 'Zig Ziglar', 'sales'),
  ('q-0141', 'Si l''échec vous apprend quelque chose, vous n''êtes pas vraiment perdant.', 'Zig Ziglar', 'mindset'),
  ('q-0142', 'Gagner n''est pas tout, mais l''effort qu''il faut fournir l''est.', 'Zig Ziglar', 'mindset'),
  ('q-0143', 'Plus vous aidez les gens à obtenir ce qu''ils désirent, plus vous avez de succès.', 'Zig Ziglar', 'sales'),
  ('q-0145', 'Le succès ne s''explique pas. L''échec ne s''excuse pas.', 'Napoleon Hill', 'mindset'),
  ('q-0146', 'Chaque difficulté porte en elle le germe d''un avantage équivalent ou supérieur.', 'Napoleon Hill', 'mindset'),
  ('q-0147', 'Les opportunités apparaissent le plus souvent sous la forme de malchance ou d''échec temporaire.', 'Napoleon Hill', 'mindset'),
  ('q-0148', 'Le monde a l''habitude de faire de la place à l''homme dont les paroles et les actions montrent qu''il sait où il va.', 'Napoleon Hill', 'mindset'),
  ('q-0151', 'S''il y a un secret à l''efficacité, c''est la concentration.', 'Peter Drucker', 'mindset'),
  ('q-0152', 'Le temps est le capital le plus rare, et si on ne sait pas le gérer, alors on ne peut rien gérer d''autre.', 'Peter Drucker', 'leadership'),
  ('q-0153', 'Le management se résume à deux fonctions : commercialiser et innover.', 'Peter Drucker', 'leadership'),
  ('q-0154', 'On obtient des résultats en exploitant des opportunités, non en résolvant des problèmes.', 'Peter Drucker', 'mindset'),
  ('q-0155', 'Il n''y a pas « un » caractère d''entrepreneur. Mais il faut « du » caractère pour l''être.', 'Peter Drucker', 'mindset'),
  ('q-0156', 'Pour être irremplaçable, il faut être différente.', 'Coco Chanel', 'mindset'),
  ('q-0157', 'La mode se démode, le style jamais.', 'Coco Chanel', 'mindset'),
  ('q-0158', 'Ma vie ne me plaisait pas, alors j''ai créé ma vie.', 'Coco Chanel', 'mindset'),
  ('q-0159', 'La force est construite par les échecs, pas par les réussites.', 'Coco Chanel', 'mindset'),
  ('q-0161', 'Un investissement dans le savoir paie toujours les meilleurs intérêts.', 'Benjamin Franklin', 'finance'),
  ('q-0162', 'Le temps, c''est de l''argent.', 'Benjamin Franklin', 'finance'),
  ('q-0163', 'Le succès est le résidu de la planification.', 'Benjamin Franklin', 'mindset'),
  ('q-0164', 'Si vous ne parvenez pas à planifier, vous prévoyez d''échouer !', 'Benjamin Franklin', 'mindset'),
  ('q-0165', 'Ne remettez pas au lendemain ce que vous pouvez faire le jour même.', 'Benjamin Franklin', 'mindset'),
  ('q-0166', 'La paresse chemine si lentement que la pauvreté la rattrape.', 'Benjamin Franklin', 'finance'),
  ('q-0168', 'Dans 20 ans, vous serez plus déçu par les choses que vous n''avez pas faites que par celles que vous avez faites.', 'H. Jackson Brown Jr.', 'mindset'),
  ('q-0170', 'Chaque fois que vous vous trouvez du côté de la majorité, il est temps de faire une pause et de réfléchir.', 'Mark Twain', 'mindset'),
  ('q-0172', 'Trop de publicité tue la publicité.', 'Jacques Séguéla', 'sales'),
  ('q-0173', 'Tout homme qui meurt riche meurt déshonoré.', 'Andrew Carnegie', 'finance'),
  ('q-0174', 'Aucun homme ne devient riche à moins qu''il enrichisse autrui.', 'Andrew Carnegie', 'finance'),
  ('q-0176', 'Faites votre devoir et un peu plus encore, et l''avenir prendra soin de lui-même.', 'Andrew Carnegie', 'mindset'),
  ('q-0177', 'Concentrez vos énergies, vos pensées et votre capital.', 'Andrew Carnegie', 'finance'),
  ('q-0178', 'Ceux qui réussissent sont des hommes qui ont choisi une ligne de conduite et qui s''y tiennent.', 'Andrew Carnegie', 'mindset'),
  ('q-0179', 'Ce n''est pas parce que les choses sont difficiles que nous n''osons pas, c''est parce que nous n''osons pas qu''elles sont difficiles.', 'Sénèque', 'mindset'),
  ('q-0180', 'Il n''est pas de vent favorable pour celui qui ne sait pas où il va.', 'Sénèque', 'mindset'),
  ('q-0181', 'C''est par l''épreuve du feu qu''on reconnaît l''or pur. C''est par les épreuves qu''on reconnaît l''homme de cœur.', 'Sénèque', 'mindset'),
  ('q-0182', 'Le plus grand obstacle à la vie est l''attente, qui espère demain et néglige aujourd''hui.', 'Sénèque', 'mindset'),
  ('q-0183', 'À force de remettre à plus tard, la vie nous dépasse.', 'Sénèque', 'mindset'),
  ('q-0184', 'C''est pendant l''orage qu''on connaît le pilote.', 'Sénèque', 'mindset'),
  ('q-0185', 'Un voyage de mille lieues commence toujours par un premier pas.', 'Lao Tseu', 'mindset'),
  ('q-0187', 'Qui triomphe de lui-même possède la force.', 'Lao Tseu', 'mindset'),
  ('q-0188', 'Tout ce que je sais, c''est que je ne sais rien.', 'Socrate', 'mindset'),
  ('q-0189', 'Connais-toi toi-même.', 'Socrate', 'mindset'),
  ('q-0190', 'Le secret du changement, c''est de concentrer toute son énergie, non pas à lutter contre le passé mais à construire l''avenir.', 'Socrate', 'mindset'),
  ('q-0191', 'Une vie sans examen ne vaut pas la peine d''être vécue.', 'Socrate', 'mindset'),
  ('q-0193', 'Sois comme un promontoire contre lequel les flots viennent sans cesse se briser.', 'Marc Aurèle', 'mindset'),
  ('q-0195', 'Avoir du courage ne veut pas dire que nous n''avons pas peur, mais que nous affrontons nos peurs.', 'Maya Angelou', 'mindset'),
  ('q-0196', 'Vous ferez face à de nombreuses défaites dans votre vie, mais ne vous laissez jamais vaincre.', 'Maya Angelou', 'mindset'),
  ('q-0197', 'Faites de votre mieux jusqu''à ce que vous en sachiez mieux. Ensuite, faites mieux.', 'Maya Angelou', 'mindset'),
  ('q-0199', 'Aussi dur que tu crois pouvoir travailler, tu peux travailler encore plus dur que ça.', 'Kobe Bryant', 'mindset'),
  ('q-0200', 'On n''abandonne pas, on ne bat en retraite, on ne fuit pas.', 'Kobe Bryant', 'mindset'),
  ('q-0201', 'Tout changement de vie commence par une décision.', 'Tony Robbins', 'mindset'),
  ('q-0202', 'L''échec est une partie du succès. Quiconque évite l''échec évite aussi le succès.', 'Tony Robbins', 'mindset'),
  ('q-0203', 'Les décisions que nous prenons déterminent notre destin.', 'Tony Robbins', 'mindset'),
  ('q-0205', 'La qualité de la vie d''une personne est en rapport direct avec sa volonté d''exceller, quel que soit le domaine où elle s''exerce.', 'Vince Lombardi', 'mindset'),
  ('q-0206', 'Si l''important n''est pas de gagner, pourquoi compte-t-on les points ?', 'Vince Lombardi', 'mindset'),
  ('q-0207', 'Les conditions essentielles pour réussir sont la patience et la certitude du succès.', 'John D. Rockefeller', 'mindset'),
  ('q-0208', 'Si vous voulez réussir, lancez-vous sur de nouveaux chemins plutôt que de parcourir les sentiers usés du succès accepté.', 'John D. Rockefeller', 'mindset'),
  ('q-0209', 'La ténacité est une des qualités indispensables pour réussir dans la vie, quel que soit le but à atteindre.', 'John D. Rockefeller', 'mindset'),
  ('q-0210', 'Le secret du succès est de faire les choses communes de manière peu commune.', 'John D. Rockefeller', 'mindset'),
  ('q-0211', 'Il n''y a qu''un seul patron : le client. Il peut licencier tout le monde, simplement en allant dépenser son argent ailleurs.', 'Sam Walton', 'sales'),
  ('q-0213', 'La meilleure raison de lancer une entreprise, c''est de créer du sens.', 'Guy Kawasaki', 'leadership'),
  ('q-0214', 'Les vrais entrepreneurs sont motivés par leur passion, non par le profit.', 'Guy Kawasaki', 'mindset'),
  ('q-0221', 'Être réaliste est la voie la plus commune vers la médiocrité.', 'Will Smith', 'mindset'),
  ('q-0224', 'Un gagnant est un rêveur qui n''abandonne jamais.', 'Nelson Mandela', 'mindset'),
  ('q-0225', 'La plus grande gloire n''est pas de ne jamais tomber, mais de se relever à chaque chute.', 'Nelson Mandela', 'mindset'),
  ('q-0226', 'Ne me jugez pas par mon succès, jugez-moi par combien de fois je suis tombé et je me suis relevé.', 'Nelson Mandela', 'mindset'),
  ('q-0227', 'C''est toujours impossible jusqu''à ce que ça soit fait.', 'Nelson Mandela', 'mindset'),
  ('q-0228', 'La confiance en soi est le premier secret du succès.', 'Ralph Waldo Emerson', 'mindset'),
  ('q-0229', 'N''allez pas là où le chemin peut mener. Allez là où il n''y a pas de chemin et laissez une trace.', 'Ralph Waldo Emerson', 'mindset'),
  ('q-0230', 'Les hommes parlent de la victoire comme d''une chance. C''est le travail qui fait la victoire.', 'Ralph Waldo Emerson', 'mindset'),
  ('q-0231', 'Rien de grand ne se fit jamais sans enthousiasme.', 'Ralph Waldo Emerson', 'mindset'),
  ('q-0232', 'L''ancêtre de toute action est une pensée.', 'Ralph Waldo Emerson', 'mindset'),
  ('q-0233', 'La vie est une aventure audacieuse ou elle n''est rien.', 'Helen Keller', 'mindset'),
  ('q-0234', 'Gardez votre visage dans le soleil et vous ne verrez pas les ombres.', 'Helen Keller', 'mindset'),
  ('q-0235', 'Aucun pessimiste n''a jamais découvert le secret des étoiles ni ouvert un nouveau chemin pour l''esprit humain.', 'Helen Keller', 'mindset'),
  ('q-0236', 'Il y a toujours deux raisons pour faire quelque chose : une bonne raison et la vraie raison !', 'Dale Carnegie', 'mindset'),
  ('q-0237', 'Ni les situations ni les gens ne peuvent être améliorés par un facteur externe. Si amélioration il doit y avoir, elle doit venir de l''intérieur.', 'Dale Carnegie', 'mindset'),
  ('q-0239', 'Un enfant, un professeur, un livre, un crayon peuvent changer le monde.', 'Malala Yousafzai', 'mindset'),
  ('q-0244', 'Les chefs d''entreprise ne peuvent pas être des spectateurs.', 'Howard Schultz', 'leadership'),
  ('q-0245', 'Parfois, vous devez créer la chose dont vous voulez faire partie.', 'Howard Schultz', 'mindset'),
  ('q-0247', 'Nous devrions construire de grandes choses qui n''existent pas.', 'Larry Page', 'mindset'),
  ('q-0248', 'Presque tous ceux qui ont eu une idée quelque peu révolutionnaire ont d''abord été traités de fous.', 'Larry Page', 'mindset'),
  ('q-0249', 'L''optimisme est important. Vous devez être un peu ridicule sur les objectifs que vous allez définir.', 'Larry Page', 'mindset'),
  ('q-0250', 'Il est très difficile d''échouer complètement, si vous visez assez haut.', 'Larry Page', 'mindset'),
  ('q-0251', 'Il vaut mieux agir trop rapidement qu''attendre trop longtemps.', 'Jack Welch', 'mindset'),
  ('q-0252', 'Restructurer, c''est un chemin, pas une destination.', 'Jack Welch', 'leadership'),
  ('q-0253', 'Contrôlez votre destinée ou quelqu''un d''autre le fera à votre place.', 'Jack Welch', 'mindset'),
  ('q-0254', 'Soit vous êtes le meilleur dans ce que vous faites, soit vous ne le faites pas très longtemps.', 'Jack Welch', 'mindset'),
  ('q-0256', 'J''attribue mon succès à ceci : je n''ai jamais présenté ou accepté aucune excuse.', 'Earl Nightingale', 'mindset'),
  ('q-0257', 'Pour augmenter votre taux de succès, vous devez augmenter votre taux d''échecs.', 'Thomas J. Watson', 'mindset'),
  ('q-0258', 'Nos clients les plus mécontents sont notre plus grande source de progrès.', 'Bill Gates', 'sales'),
  ('q-0259', 'On ne devient homme qu''en se surpassant.', 'Aristote', 'mindset'),
  ('q-0260', 'La stratégie, c''est l''art de faire face à son destin.', 'Peter Drucker', 'leadership'),
  ('q-0261', 'Il faut toujours être prêt à négocier, mais ne jamais négocier sans être prêt.', 'Richard Nixon', 'sales'),
  ('q-0262', 'Vous pouvez tromper tout le monde une fois, quelques-uns souvent, mais jamais tout le monde tout le temps.', 'Abraham Lincoln', 'mindset'),
  ('q-0263', 'Gagner de l''argent est un art, travailler est un art et faire de bonnes affaires est le plus bel art.', 'Andy Warhol', 'finance'),
  ('q-0264', 'Le secret des affaires est de savoir quelque chose que personne ne sait.', 'Aristote Onassis', 'finance'),
  ('q-0265', 'Vous n''êtes jamais trop vieux pour fixer un nouvel objectif ou rêver un nouveau rêve.', 'C.S. Lewis', 'mindset'),
  ('q-0266', 'Seul, nous pouvons faire si peu ; ensemble, nous pouvons faire tant.', 'Helen Keller', 'leadership'),
  ('q-0267', 'Le succès n''est pas la clé du bonheur. Le bonheur est la clé du succès.', 'Albert Schweitzer', 'mindset'),
  ('q-0268', 'La seule limite à notre réalisation de demain sera nos doutes d''aujourd''hui.', 'Franklin D. Roosevelt', 'mindset'),
  ('q-0269', 'Ce n''est pas que je sois si intelligent, c''est juste que je reste avec les problèmes plus longtemps.', 'Albert Einstein', 'mindset'),
  ('q-0270', 'Le succès est la somme de petits efforts, répétés jour après jour.', 'Robert Collier', 'mindset'),
  ('q-0271', 'La force de l''équipe, c''est chaque membre. La force de chaque membre, c''est l''équipe.', 'Phil Jackson', 'leadership'),
  ('q-0272', 'Fixer des objectifs est le premier pas pour transformer l''invisible en visible.', 'Tony Robbins', 'mindset'),
  ('q-0273', 'L''avenir appartient à ceux qui croient à la beauté de leurs rêves.', 'Eleanor Roosevelt', 'mindset'),
  ('q-0274', 'Croyez que vous pouvez et vous êtes déjà à mi-chemin.', 'Theodore Roosevelt', 'mindset'),
  ('q-0275', 'Ce qui est derrière nous et ce qui est devant nous sont de petites choses comparées à ce qui est en nous.', 'Ralph Waldo Emerson', 'mindset'),
  ('q-0276', 'Si ce que vous faites ne vous rapproche pas de vos buts, alors c''est que ça vous en éloigne.', 'Brian Tracy', 'mindset'),
  ('q-0277', 'En matière commerciale, le succès vient davantage de l''attitude que de l''aptitude.', 'Michael Aguilar', 'sales'),
  ('q-0278', 'Les 5 freins à toute vente : pas de besoin, pas de budget, pas d''urgence, pas d''envie, pas de confiance.', 'Zig Ziglar', 'sales'),
  ('q-0279', 'Si les gens vous apprécient, ils vous écouteront, mais s''ils ont confiance en vous, ils feront affaire avec vous.', 'Zig Ziglar', 'sales'),
  ('q-0280', 'La vente est essentiellement un transfert de sentiments.', 'Zig Ziglar', 'sales'),
  ('q-0281', 'Nous considérons nos clients comme des invités, à une fête où nous sommes les hôtes.', 'Jeff Bezos', 'sales'),
  ('q-0282', 'Mettre le client en premier. Inventer. Et être patient.', 'Jeff Bezos', 'sales'),
  ('q-0283', 'Ne trouvez pas des clients pour vos produits, trouvez des produits pour vos clients.', 'Seth Godin', 'sales'),
  ('q-0284', 'Nous plaçons le client en numéro un, l''employé en numéro deux, l''actionnaire en numéro trois.', 'Jack Ma', 'sales'),
  ('q-0285', 'On se souvient de la qualité bien plus longtemps que du prix.', 'Guccio Gucci', 'sales'),
  ('q-0286', 'La meilleure des publicités est un client satisfait.', 'Bill Gates', 'sales'),
  ('q-0287', 'Il ne sert à rien d''être le meilleur si on est le seul à le savoir.', 'Richard Branson', 'sales'),
  ('q-0288', 'Savoir écouter, c''est posséder, outre le sien, le cerveau des autres.', 'Léonard de Vinci', 'sales'),
  ('q-0289', 'L''entreprise est élue tous les jours par ses clients.', 'François Michelin', 'sales'),
  ('q-0290', 'La philosophie commerciale nous enseigne que celui qui ne demande rien n''a rien, et il est déçu.', 'Jean-Jacques Servan-Schreiber', 'sales'),
  ('q-0292', 'Quand on ne sait pas où on va, tous les chemins mènent un peu nulle part.', 'Henry Kissinger', 'leadership'),
  ('q-0293', 'Si vous voulez vous élever, élevez quelqu''un d''autre.', 'Booker T. Washington', 'leadership'),
  ('q-0294', 'L''attitude détermine les actions. Les actions déterminent les résultats.', 'Jim Rohn', 'leadership'),
  ('q-0295', 'Un leader est quelqu''un qui connaît le chemin, qui suit le chemin, et qui montre le chemin.', 'John C. Maxwell', 'leadership'),
  ('q-0296', 'Si vous ne pouvez pas contrôler vos émotions, vous ne pouvez pas contrôler votre argent.', 'Warren Buffett', 'finance'),
  ('q-0297', 'Règle numéro un : ne perdez jamais d''argent. Règle numéro deux : n''oubliez jamais la règle numéro un.', 'Warren Buffett', 'finance'),
  ('q-0299', 'En bourse, tu as deux choix : t''enrichir lentement ou t''appauvrir rapidement.', 'Benjamin Graham', 'finance'),
  ('q-0300', 'La chance ne sourit qu''aux esprits bien préparés.', 'Louis Pasteur', 'mindset'),
  ('q-0301', 'L''enthousiasme est une maladie contagieuse.', 'Voltaire', 'mindset'),
  ('q-0302', 'Accepter l''idée de la défaite, c''est être déjà vaincu.', 'Général Foch', 'mindset'),
  ('q-0303', 'Ne pensez pas à l''échec, pensez aux opportunités que vous risquez de manquer.', 'Jack Canfield', 'mindset'),
  ('q-0304', 'Vous risquez d''être déçu si vous échouez, mais vous êtes condamné si vous n''essayez pas.', 'Beverly Sills', 'mindset'),
  ('q-0305', 'Être conscient de son ignorance est le premier pas vers la connaissance.', 'Benjamin Disraeli', 'mindset'),
  ('q-0307', 'Les réussites spectaculaires sont toujours précédées de préparations peu spectaculaires.', 'Chamfort', 'mindset'),
  ('q-0308', 'La façon la plus courante d''abandonner son pouvoir, c''est de penser qu''on n''en a pas.', 'Alice Walker', 'mindset'),
  ('q-0312', 'Le leadership n''a rien à voir avec les titres. C''est la capacité à influencer d''autres vies.', 'John C. Maxwell', 'leadership'),
  ('q-0314', 'À une époque, le leadership résidait dans les muscles. Aujourd''hui, il réside dans la façon de traiter les gens.', 'Mahatma Gandhi', 'leadership'),
  ('q-0315', 'Diriger, c''est servir.', 'Sénèque', 'leadership'),
  ('q-0316', 'Le leader est celui qui sait inspirer sans éteindre, diriger sans écraser.', 'Maya Angelou', 'leadership'),
  ('q-0317', 'Les gens n''achètent pas ce que vous faites, ils achètent pourquoi vous le faites.', 'Simon Sinek', 'leadership'),
  ('q-0318', 'La fonction du leadership est de produire d''autres leaders, pas plus de suiveurs.', 'Ralph Nader', 'leadership'),
  ('q-0319', 'Tout le monde porte un panneau invisible autour du cou qui dit : faites-moi sentir que je suis important.', 'Mary Kay Ash', 'leadership'),
  ('q-0320', 'Avant d''être un leader, le succès consiste à se développer soi-même. Une fois leader, le succès consiste à faire grandir les autres.', 'Jack Welch', 'leadership'),
  ('q-0321', 'Les leaders ne naissent pas, ils sont faits. Et ils sont faits par l''effort acharné.', 'Vince Lombardi', 'leadership'),
  ('q-0322', 'Soyez craintifs quand les autres sont avides. Soyez avide quand les autres sont craintifs.', 'Warren Buffett', 'finance'),
  ('q-0323', 'Si vous n''êtes pas prêt à détenir une action pendant 10 ans, ne pensez même pas à la détenir pendant 10 minutes.', 'Warren Buffett', 'finance'),
  ('q-0324', 'Il ne s''agit pas de prédire la pluie, il s''agit de construire l''arche.', 'Warren Buffett', 'finance'),
  ('q-0325', 'Les quatre mots les plus dangereux dans le monde de l''investissement sont : « cette fois, c''est différent ».', 'John Templeton', 'finance'),
  ('q-0326', 'La patience est la clé de l''investissement réussi.', 'John Templeton', 'finance'),
  ('q-0327', 'Ne cherchez pas l''aiguille dans la meule de foin : achetez la meule.', 'John C. Bogle', 'finance'),
  ('q-0328', 'Investissez dans ce que vous connaissez.', 'Peter Lynch', 'finance'),
  ('q-0329', 'Investir n''est pas battre les autres à leur jeu. Il s''agit de se contrôler soi-même.', 'Benjamin Graham', 'finance'),
  ('q-0330', 'Les riches investissent leur argent et dépensent ce qui reste.', 'Robert Kiyosaki', 'finance'),
  ('q-0331', 'Les pauvres et la classe moyenne travaillent pour de l''argent. Les riches font travailler l''argent.', 'Robert Kiyosaki', 'finance'),
  ('q-0332', 'L''éducation obligatoire amène un salaire, l''éducation personnelle amène la fortune.', 'Robert Kiyosaki', 'finance'),
  ('q-0333', 'L''important n''est pas d''avoir raison ou tort, mais de savoir combien d''argent on gagne quand on a raison.', 'George Soros', 'finance'),
  ('q-0334', 'Le moment d''acheter, c''est quand le sang coule dans les rues.', 'Nathan Rothschild', 'finance'),
  ('q-0335', 'On apprend beaucoup plus de ses pertes que de ses gains.', 'Paul Tudor Jones', 'finance'),
  ('q-0336', 'N''essayez pas d''acheter aux points bas et de vendre aux points hauts. Seuls les menteurs peuvent faire ça.', 'Bernard Baruch', 'finance'),
  ('q-0337', 'La vente commence quand le client dit : non.', 'Elmer G. Leterman', 'sales'),
  ('q-0338', 'La raison d''être d''une entreprise est de créer et de garder un client.', 'Théodore Levitt', 'sales'),
  ('q-0339', 'Prenez soin du client et l''entreprise prendra soin d''elle-même.', 'Ray Kroc', 'sales'),
  ('q-0340', 'Le service client ne doit pas être uniquement un service, il doit concerner l''ensemble de l''entreprise.', 'Tony Hsieh', 'sales'),
  ('q-0341', 'Un client qui n''a qu''un seul fournisseur cesse d''être intelligent.', 'François Michelin', 'sales'),
  ('q-0342', 'Ce qui compte, c''est le chiffre un : une tasse, un client, un partenaire.', 'Howard Schultz', 'sales'),
  ('q-0344', 'Un objectif correctement défini est à moitié atteint.', 'Zig Ziglar', 'sales'),
  ('q-0345', 'Pour une vente manquée par excès d''enthousiasme, on en compte cent manquées par faute d''enthousiasme.', 'Zig Ziglar', 'sales'),
  ('q-0346', 'Le marketing ne consiste pas à vendre ce que vous produisez, mais à connaître ce dont le consommateur a besoin.', 'Philip Kotler', 'sales'),
  ('q-0347', 'L''objectif de la vente est de satisfaire un besoin client, celui du marketing est de comprendre ce besoin.', 'Philip Kotler', 'sales'),
  ('q-0348', 'Le marketing peut s''apprendre en une heure ; il faut toute une vie pour le maîtriser.', 'Philip Kotler', 'sales'),
  ('q-0349', 'Il est impossible d''être chef d''entreprise sans un minimum d''audace.', 'Carlos Ghosn', 'leadership'),
  ('q-0351', 'Si vous vous limitez aux avis des experts, il y a peu de chances que vous innoviez.', 'Carlos Ghosn', 'leadership'),
  ('q-0352', 'Une équipe n''est pas un groupe de personnes qui travaillent ensemble. C''est un groupe de personnes qui se font confiance.', 'Simon Sinek', 'leadership'),
  ('q-0353', 'Un chef possède un titre, un leader a les autres avec lui.', 'Simon Sinek', 'leadership'),
  ('q-0354', 'Bâtir la confiance ne réclame rien de plus que de dire la vérité.', 'Simon Sinek', 'leadership'),
  ('q-0356', 'Les managers travaillent avec les processus, les leaders travaillent avec les gens.', 'John C. Maxwell', 'leadership'),
  ('q-0357', 'Pour réaliser une grande vision, vous devez avoir une grande équipe.', 'John C. Maxwell', 'leadership'),
  ('q-0358', 'La confiance est le fondement de tout bon leadership.', 'John C. Maxwell', 'leadership'),
  ('q-0359', 'Investissez dans une entreprise que n''importe quel imbécile peut diriger, parce qu''un jour un imbécile le fera.', 'Charlie Munger', 'finance'),
  ('q-0360', 'Si investir était si simple, tout le monde serait riche.', 'Charlie Munger', 'finance'),
  ('q-0361', 'Le gros argent n''est pas dans l''achat ou la vente, mais dans l''attente.', 'Charlie Munger', 'finance'),
  ('q-0362', 'Vous n''avez pas besoin d''être brillant, juste un peu plus sage que les autres, en moyenne, pendant longtemps.', 'Charlie Munger', 'finance'),
  ('q-0363', 'Les riches acquièrent des actifs. Les pauvres et la classe moyenne acquièrent des passifs en pensant que ce sont des actifs.', 'Robert Kiyosaki', 'finance'),
  ('q-0364', 'Ce qui compte, ce n''est pas combien d''argent vous faites, mais combien vous parvenez à en conserver.', 'Robert Kiyosaki', 'finance'),
  ('q-0365', 'Vous devez voir l''échec comme le début et le milieu, mais ne jamais le considérer comme une fin.', 'Jessica Herrin', 'mindset'),
  ('q-0366', 'Peu importe combien de fois vous avez échoué. Vous devez juste avoir raison une fois.', 'Mark Cuban', 'mindset'),
  ('q-0367', 'La croissance et le confort ne coexistent pas.', 'Virginia Rometty', 'mindset'),
  ('q-0368', 'Le succès arrive généralement à ceux qui sont trop occupés pour le chercher.', 'Henry David Thoreau', 'mindset'),
  ('q-0369', 'Je n''ai jamais rêvé de succès. J''ai travaillé pour cela.', 'Estée Lauder', 'mindset'),
  ('q-0371', 'Il y a cette joie qui vient de s''asseoir pour résoudre un problème, et de se lever quand c''est fait et que c''est bon.', 'Drew Houston', 'mindset'),
  ('q-0372', 'Ne soyez jamais limité par l''imagination limitée des autres.', 'Mae Jemison', 'mindset'),
  ('q-0373', 'J''ai toujours fait quelque chose que je n''étais pas tout à fait prête à faire. Je pense que c''est comme ça qu''on grandit.', 'Marissa Mayer', 'mindset'),
  ('q-0374', 'Il n''y a pas de meilleure mesure de vos valeurs que la façon dont vous dépensez votre temps.', 'Scott Belsky', 'mindset'),
  ('q-0375', 'Une idée ne peut devenir une réalité qu''une fois qu''elle est décomposée en éléments organisés et actionnables.', 'Scott Belsky', 'leadership'),
  ('q-0378', 'Être sans peur n''est pas l''absence de peur. C''est la maîtrise de la peur. C''est se relever une fois de plus que nous tombons.', 'Arianna Huffington', 'mindset'),
  ('q-0379', 'La persévérance n''est pas une longue course ; c''est plusieurs courses courtes les unes après les autres.', 'Walter Elliot', 'mindset'),
  ('q-0380', 'Le succès n''est pas une question de grandeur. C''est une question de constance.', 'Dwayne Johnson', 'mindset'),
  ('q-0382', 'Seuls ceux qui prennent le risque d''aller trop loin peuvent découvrir jusqu''où ils peuvent aller.', 'T.S. Eliot', 'mindset'),
  ('q-0383', 'La plus grande erreur que vous puissiez faire dans la vie, c''est d''avoir peur de faire des erreurs.', 'John Wooden', 'mindset'),
  ('q-0384', 'L''échec est la clé du succès ; chaque erreur nous enseigne quelque chose.', 'Morihei Ueshiba', 'mindset'),
  ('q-0385', 'Ne jugez pas chaque jour à la récolte que vous faites, mais aux graines que vous plantez.', 'Robert Louis Stevenson', 'mindset'),
  ('q-0386', 'La question n''est pas « qui va me donner l''autorisation de faire ça ? » mais plutôt « qui pourra m''arrêter ? »', 'Ayn Rand', 'mindset'),
  ('q-0389', 'La réussite ne se mesure pas à l''argent que vous gagnez mais à votre capacité à changer la vie des gens.', 'Michelle Obama', 'mindset'),
  ('q-0390', 'Créez votre propre définition du succès, agissez selon vos propres règles, et construisez la vie dont vous êtes fière.', 'Anne Sweeney', 'mindset'),
  ('q-0392', 'La meilleure façon de prédire l''avenir est de l''inventer.', 'Alan Kay', 'mindset'),
  ('q-0393', 'Ne te demande pas ce dont le monde a besoin. Ce dont il a besoin, ce sont des gens qui ont trouvé ce qui les fait vivre pleinement.', 'Howard Thurman', 'mindset'),
  ('q-0394', 'Si vous ne construisez pas votre rêve, quelqu''un d''autre vous embauchera pour construire les siens.', 'Tony Gaskins', 'mindset'),
  ('q-0395', 'Il n''est jamais trop tard pour être ce que vous auriez pu être.', 'George Eliot', 'mindset'),
  ('q-0398', 'Si l''on doit se souvenir de tous ses échecs, on ne s''en sort pas.', 'Xavier Niel', 'mindset'),
  ('q-0399', 'Il faut avoir le courage de prendre des risques et de ne pas avoir peur de l''échec.', 'Marc Simoncini', 'mindset'),
  ('q-0400', 'Point n''est besoin d''espérer pour entreprendre, ni de réussir pour persévérer.', 'Guillaume Ier d''Orange-Nassau', 'mindset'),
  ('q-0401', 'Si les opportunités ne frappent pas à la porte, construisez une nouvelle porte.', 'Milton Berle', 'mindset'),
  ('q-0402', 'Si tout semble sous contrôle, c''est que vous n''allez pas assez vite.', 'Mario Andretti', 'mindset'),
  ('q-0403', 'Il n''y a pas meilleur catalyseur du succès que la curiosité.', 'Michael Dell', 'mindset'),
  ('q-0404', 'Il est possible dans certains cas d''être occupé, très occupé, et parfaitement inefficace.', 'Stephen Covey', 'mindset'),
  ('q-0405', 'La mort de l''entrepreneur porte un nom : isolement.', 'Ernesto Sirolli', 'mindset'),
  ('q-0406', 'Certains rêvent d''incroyables réalisations, pendant que d''autres restent éveillés et les font.', 'Nolan Bushnell', 'mindset'),
  ('q-0407', 'L''inspiration est périssable. Agissez immédiatement.', 'Naval Ravikant', 'mindset'),
  ('q-0408', 'L''échec n''est rien d''autre que la façon dont la vie vous indique que vous n''êtes pas sur la bonne voie.', 'Sara Blakely', 'mindset'),
  ('q-0409', 'Ne soyez pas intimidé par ce que vous ne savez pas. Cela peut être votre plus grande force.', 'Sara Blakely', 'mindset'),
  ('q-0410', 'L''entrepreneur est cette personne qui saute d''une falaise, et construit un avion au cours de sa chute.', 'Reid Hoffman', 'mindset'),
  ('q-0411', 'La volonté, c''est le clou auquel on accroche son projet pour l''avoir toujours devant les yeux.', 'Victor Hugo', 'mindset'),
  ('q-0412', 'L''histoire, c''est la rencontre d''une volonté et d''un événement.', 'Charles de Gaulle', 'mindset'),
  ('q-0413', 'Délibérer est le fait de plusieurs. Agir est le fait d''un seul.', 'Charles de Gaulle', 'leadership'),
  ('q-0414', 'Si tu veux construire un bateau, ne rassemble pas des hommes pour aller chercher du bois, mais donne-leur envie de la mer immense.', 'Antoine de Saint-Exupéry', 'mindset'),
  ('q-0415', 'Il faut d''abord savoir ce que l''on veut, il faut ensuite avoir le courage de le dire, il faut ensuite l''énergie de le faire.', 'Georges Clemenceau', 'mindset'),
  ('q-0416', 'Évoluer est la plus grande réussite d''une vie, et sa plus belle récompense.', 'Ray Dalio', 'mindset'),
  ('q-0417', 'L''échec signifie un dépouillement de l''inessentiel.', 'J.K. Rowling', 'mindset'),
  ('q-0419', 'Le succès recèle le germe de sa propre destruction.', 'Andrew Grove', 'mindset'),
  ('q-0420', 'Seuls ceux qui dorment ne font pas d''erreurs.', 'Ingvar Kamprad', 'mindset'),
  ('q-0425', 'Le succès est fait de 99 % d''échecs.', 'Soichiro Honda', 'mindset'),
  ('q-0426', 'Nous avons plus de force que de volonté.', 'La Rochefoucauld', 'mindset'),
  ('q-0427', 'Les occasions se présentent habituellement sous la forme d''un dur labeur ; c''est pourquoi la plupart des gens ne les reconnaissent pas.', 'Ann Landers', 'mindset'),
  ('q-0429', 'Il ne dépend pas de toi d''être riche, mais il dépend de toi d''être heureux.', 'Epictète', 'mindset'),
  ('q-0431', 'Les rêves ne sont pas ce que vous voyez dans votre sommeil, les rêves sont des choses qui ne vous permettent pas de dormir.', 'Cristiano Ronaldo', 'mindset'),
  ('q-0433', 'Travailler dur bat le talent quand le talent ne travaille pas.', 'Usain Bolt', 'mindset'),
  ('q-0434', 'Le présent n''est pas un passé en puissance, il est le moment du choix et de l''action.', 'Simone de Beauvoir', 'mindset'),
  ('q-0436', 'La vraie grandeur consiste à être maître de soi-même.', 'Daniel Defoe', 'mindset'),
  ('q-0437', 'Toute facilité apparente, toute réussite, sont les fruits d''une rigueur intime.', 'Gérard Bauer', 'mindset'),
  ('q-0439', 'Si on veut vivre, il faut prendre des risques.', 'Boris Cyrulnik', 'mindset'),
  ('q-0440', 'Je patine là où la rondelle ira, pas où elle est.', 'Wayne Gretzky', 'mindset'),
  ('q-0442', 'Le parcours était semé d''embûches, mais c''était mal me connaître que d''imaginer que j''abandonnerais la partie dès les premiers obstacles.', 'Simone Veil', 'mindset'),
  ('q-0443', 'Le progrès est impossible sans changement et ceux qui ne peuvent changer leur esprit ne peuvent absolument rien changer.', 'George Bernard Shaw', 'mindset'),
  ('q-0444', 'Trop souvent, les gens travaillent dur sur la mauvaise chose. Travailler sur la bonne chose est probablement plus important que de travailler dur.', 'Caterina Fake', 'mindset'),
  ('q-0451', 'Les entrepreneurs ne demandent pas la permission. Ils agissent pour leur mission.', 'Ryan Lilly', 'mindset'),
  ('q-0455', 'Celui qui n''a jamais commis d''erreur n''a jamais tenté quelque chose de nouveau.', 'François Mitterrand', 'mindset'),
  ('q-0456', 'L''espérance est un risque à courir.', 'Georges Bernanos', 'mindset'),
  ('q-0457', 'Le talent, c''est d''avoir envie de faire quelque chose.', 'Jacques Brel', 'mindset'),
  ('q-0458', 'Il faut toujours viser la lune, car même en cas d''échec, on atterrit dans les étoiles.', 'Jean d''Ormesson', 'mindset'),
  ('q-0460', 'Agir librement, c''est prendre possession de soi.', 'Henri Bergson', 'mindset'),
  ('q-0461', 'Oser, c''est d''abord oser l''échec.', 'Charles Pépin', 'mindset'),
  ('q-0462', 'La seule chose promise d''avance à l''échec, c''est celle que l''on ne tente pas.', 'Paul-Émile Victor', 'mindset'),
  ('q-0464', 'Oser, c''est perdre pied momentanément. Ne pas oser, c''est se perdre soi-même.', 'Søren Kierkegaard', 'mindset'),
  ('q-0465', 'On ne réussit ordinairement dans les grandes entreprises qu''en courant de grands dangers.', 'Hérodote', 'mindset'),
  ('q-0466', 'Il faut un peu risquer dans la vie, quand on veut avoir quelque chose.', 'Marcel Pagnol', 'mindset'),
  ('q-0467', 'On hasarde de perdre en voulant trop gagner.', 'Jean de La Fontaine', 'mindset'),
  ('q-0468', 'Le leadership consiste à rendre les autres meilleurs en sa présence et à faire en sorte que cet impact dure en son absence.', 'Sheryl Sandberg', 'leadership'),
  ('q-0470', 'Le leadership, c''est l''art de motiver quelqu''un à faire ce que vous voulez qu''il fasse parce qu''il veut le faire.', 'Dwight Eisenhower', 'leadership'),
  ('q-0471', 'Le leadership n''est pas une position, mais une action.', 'Donald McGannon', 'leadership'),
  ('q-0473', 'Il est difficile de rencontrer des objectifs que vous n''avez jamais définis.', 'Susan Wojcicki', 'leadership'),
  ('q-0474', 'Le secret de la réussite est de savoir s''entourer de gens meilleurs que soi.', 'François Pinault', 'leadership'),
  ('q-0478', 'Le bien est l''ennemi du mieux.', 'Jim Collins', 'leadership'),
  ('q-0482', 'L''innovation n''est pas une fin en soi. Encore faut-il la développer pour l''imposer aux clients.', 'Akio Morita', 'leadership'),
  ('q-0483', 'Diriger, c''est se dévouer à une idée, à un rêve, à une vision de ce qui peut advenir.', 'John Fitzgerald Kennedy', 'leadership'),
  ('q-0485', 'La confiance rapporte plus que le contrôle.', 'Jean-François Zobrist', 'leadership'),
  ('q-0487', 'Gagner de l''argent n''est pas une chose que l''on fait, c''est une compétence que l''on apprend.', 'Naval Ravikant', 'finance'),
  ('q-0488', 'La confiance ! C''est ça qui est important, plus que les capitaux propres ou les liquidités.', 'Phil Knight', 'finance'),
  ('q-0489', 'Gagner de l''argent n''oblige personne à salir son honneur ou sa conscience.', 'Guy de Rothschild', 'finance'),
  ('q-0490', 'Après tout, l''argent disparaît, des amis meurent et vous mourez vous-même, mais votre réputation demeure.', 'Thor Bjorgolfsson', 'finance'),
  ('q-0491', 'Faire de l''argent un moyen et non une fin.', 'Pierre Rabhi', 'finance'),
  ('q-0493', 'Les riches se concentrent sur les solutions, les pauvres se concentrent sur les problèmes.', 'T. Harv Eker', 'finance'),
  ('q-0494', 'L''argent, c''est la liberté monnayée.', 'Fiodor Dostoïevski', 'finance'),
  ('q-0495', 'N''estime l''argent ni plus ni moins qu''il ne vaut : c''est un bon serviteur et un mauvais maître.', 'Alexandre Dumas', 'finance'),
  ('q-0496', 'L''argent qu''on possède est celui de la liberté ; celui qu''on pourchasse est celui de la servitude.', 'Jean-Jacques Rousseau', 'finance'),
  ('q-0497', 'Quand j''étais jeune, je croyais que, dans la vie, l''argent était le plus important. Maintenant que je suis vieux, je le sais !', 'Oscar Wilde', 'finance'),
  ('q-0498', 'Il y a tellement de choses plus importantes dans la vie que l''argent, mais il faut tellement d''argent pour les acquérir.', 'Groucho Marx', 'finance'),
  ('q-0499', 'Juste parce que vous pouvez vous le permettre ne signifie pas que vous devez l''acheter.', 'Suze Orman', 'finance'),
  ('q-0500', 'Ma philosophie d''investissement, généralement, avec des exceptions, est d''acheter quelque chose quand personne n''en veut.', 'Carl Icahn', 'finance'),
  ('q-0503', 'Privilégiez le client, non la vente.', 'Katherine Barchetti', 'sales'),
  ('q-0504', 'Ne célébrez pas la clôture d''une vente, célébrez l''ouverture d''une relation.', 'Patricia Fripp', 'sales'),
  ('q-0507', 'Si vous ne prenez pas soin de votre client, votre concurrent le fera.', 'Bob Hooey', 'sales'),
  ('q-0508', 'Intéressez-vous à créer de la valeur pour vos clients. Si vous comprenez bien cette partie, la vente est facile.', 'Anthony Iannarino', 'sales'),
  ('q-0509', 'Les grands vendeurs sont des créateurs de relations qui apportent de la valeur et aident leurs clients à gagner.', 'Jeffrey Gitomer', 'sales'),
  ('q-0510', 'L''éthique et les valeurs d''un vendeur contribuent davantage au succès des ventes que les techniques ou les stratégies.', 'Ron Willingham', 'sales'),
  ('q-0511', 'Les meilleures questions de vente témoignent de votre expertise.', 'Jill Konrath', 'sales'),
  ('q-0512', 'Ne vous plaignez jamais d''un client difficile, car il est la cause de vos progrès.', 'Auguste Detoeuf', 'sales'),
  ('q-0513', 'Parler est un besoin, écouter est un art.', 'Goethe', 'sales'),
  ('q-0514', 'Les clients ne se soucient pas du tout de savoir si vous concluez la transaction ou non. Ils se soucient d''améliorer leur entreprise.', 'Aaron Ross', 'sales'),
  ('q-0516', 'Être premier sur un marché n''est pas tout. La fidélité des clients est tout.', 'Stefan Persson', 'sales'),
  ('q-0518', 'Dire la vérité est la meilleure campagne marketing.', 'Richie Norton', 'sales'),
  ('q-0519', 'Le bon entrepreneur, c''est vous : il n''y a pas de profil type pour réussir.', 'Xavier Niel', 'mindset'),
  ('q-0520', 'On peut casser les codes d''un secteur et oser ce que personne n''a osé faire.', 'Xavier Niel', 'leadership'),
  ('q-0522', 'L''échec n''est pas le contraire du succès, c''est une étape nécessaire pour y parvenir.', 'Marc Simoncini', 'mindset'),
  ('q-0524', 'Le cœur a ses raisons que la raison ne connaît point.', 'Blaise Pascal', 'mindset'),
  ('q-0525', 'L''essentiel est invisible pour les yeux.', 'Antoine de Saint-Exupéry', 'mindset'),
  ('q-0526', 'Fais de ta vie un rêve, et d''un rêve, une réalité.', 'Antoine de Saint-Exupéry', 'mindset'),
  ('q-0527', 'L''ambition s''accorde mal avec la paresse.', 'La Rochefoucauld', 'mindset'),
  ('q-0529', 'Ne pas avoir peur d''échouer compte plus que ce qu''on apprend à l''école.', 'Sara Blakely', 'mindset'),
  ('q-0531', 'Terminé vaut mieux que parfait : mieux vaut avancer qu''attendre la perfection.', 'Sheryl Sandberg', 'mindset'),
  ('q-0532', 'Demandez-vous : que ferais-je si je n''avais pas peur ? Puis faites-le.', 'Sheryl Sandberg', 'mindset'),
  ('q-0534', 'Si vous n''avez pas honte de la première version de votre produit, vous avez lancé trop tard.', 'Reid Hoffman', 'leadership'),
  ('q-0535', 'L''échec n''est pas l''opposé de la réussite, il en fait partie.', 'Arianna Huffington', 'mindset'),
  ('q-0536', 'Le succès peut pousser à désapprendre les habitudes qui nous ont fait réussir.', 'Satya Nadella', 'mindset'),
  ('q-0537', 'Il faut passer d''une culture du tout savoir à une culture du tout apprendre.', 'Satya Nadella', 'leadership'),
  ('q-0539', 'On peut se focaliser sur les obstacles, ou se concentrer pour franchir le mur.', 'Tim Cook', 'mindset'),
  ('q-0540', 'Le poison le plus dangereux, c''est le sentiment d''avoir réussi.', 'Ingvar Kamprad', 'mindset'),
  ('q-0541', 'Le temps est votre ressource la plus précieuse : une fois perdu, il est perdu pour de bon.', 'Ingvar Kamprad', 'mindset'),
  ('q-0544', 'Personne ne voit l''entrepreneuriat comme une survie, pourtant c''est exactement ça.', 'Anita Roddick', 'leadership'),
  ('q-0545', 'Il est impossible de vivre sans jamais échouer, à moins de vivre trop prudemment pour vivre vraiment.', 'J.K. Rowling', 'mindset'),
  ('q-0546', 'Notre seul vrai plan stratégique, c''est d''agir, tout simplement.', 'Herb Kelleher', 'leadership'),
  ('q-0547', 'Le succès est lié à l''action : ceux qui réussissent avancent sans cesse, malgré les erreurs.', 'Conrad Hilton', 'mindset'),
  ('q-0548', 'Faites des erreurs, mais faites-les plus vite que les autres.', 'Andrew Grove', 'mindset'),
  ('q-0549', 'Jouez des jeux à long terme, avec des gens qui jouent aussi le long terme.', 'Naval Ravikant', 'mindset'),
  ('q-0550', 'Recherchez la richesse, pas l''argent ni le statut.', 'Naval Ravikant', 'finance'),
  ('q-0551', 'Le revenu est la meilleure forme de financement.', 'Naval Ravikant', 'finance'),
  ('q-0552', 'Dans une startup, l''exécution est tout.', 'Paul Graham', 'leadership'),
  ('q-0553', 'N''embauchez pas de génies toxiques : le coût pour l''esprit d''équipe est trop élevé.', 'Reed Hastings', 'leadership'),
  ('q-0555', 'Mon but n''est pas d''échouer vite, mais de réussir sur la durée : ce n''est pas la même chose.', 'Marc Andreessen', 'leadership'),
  ('q-0556', 'Les mauvais managers embauchent de très mauvais employés car ils se sentent menacés par les meilleurs.', 'Marc Andreessen', 'leadership'),
  ('q-0557', 'Chaque décision difficile mais juste vous rend un peu plus courageux.', 'Ben Horowitz', 'mindset'),
  ('q-0558', 'Un fondateur doit croire qu''une solution existe et la chercher, sans se soucier des probabilités.', 'Ben Horowitz', 'leadership'),
  ('q-0559', 'Toute grande entreprise repose sur un secret caché du reste du monde.', 'Peter Thiel', 'mindset'),
  ('q-0560', 'La concurrence tue les profits ; visez plutôt un monopole créatif qui profite à tous.', 'Peter Thiel', 'finance'),
  ('q-0561', 'On voulait des voitures volantes, on a eu 140 caractères.', 'Peter Thiel', 'mindset'),
  ('q-0562', 'Si ça ne vend pas, ce n''est pas créatif.', 'David Ogilvy', 'sales'),
  ('q-0563', 'Dites la vérité, mais rendez-la fascinante : on n''achète pas ce qui nous ennuie.', 'David Ogilvy', 'sales'),
  ('q-0564', 'Si chacun de nous embauche des gens plus petits que lui, nous deviendrons une entreprise de nains.', 'David Ogilvy', 'leadership'),
  ('q-0565', 'Les grands battants sont portés non par la quête du succès, mais par la peur de l''échec.', 'Larry Ellison', 'mindset'),
  ('q-0566', 'Quand on innove, il faut être prêt à ce que tout le monde vous dise que vous êtes fou.', 'Larry Ellison', 'mindset'),
  ('q-0567', 'Pas besoin d''être un génie ou un visionnaire pour réussir : il faut un cadre et un rêve.', 'Michael Dell', 'mindset'),
  ('q-0568', 'Les entreprises réussissent ou échouent selon leur capacité à transformer la donnée en décisions.', 'Michael Dell', 'leadership'),
  ('q-0569', 'Le but du marketing est de rendre la vente superflue.', 'Peter Drucker', 'sales'),
  ('q-0570', 'Les gens détestent qu''on leur vende, mais ils adorent acheter.', 'Jeffrey Gitomer', 'sales'),
  ('q-0571', 'Le marketing ne consiste plus à parler des produits que vous fabriquez, mais à raconter des histoires.', 'Seth Godin', 'sales'),
  ('q-0572', 'Approchez chaque client avec l''idée de l''aider à résoudre un problème, pas de lui vendre un produit.', 'Brian Tracy', 'sales'),
  ('q-0573', 'Faites de votre client le héros de votre histoire.', 'Ann Handley', 'sales'),
  ('q-0574', 'La meilleure publicité est celle que font les clients satisfaits.', 'Philip Kotler', 'sales'),
  ('q-0575', 'Si vous essayez de plaire à tout le monde, vous n''intéresserez personne.', 'Seth Godin', 'sales'),
  ('q-0576', 'Vendre, ce n''est pas convaincre quelqu''un d''acheter, c''est l''aider à décider.', 'Zig Ziglar', 'sales'),
  ('q-0577', 'La qualité d''un service se mesure à la façon dont on répare ses erreurs.', 'Donald Porter', 'sales'),
  ('q-0578', 'Rapprochez-vous plus que jamais de vos clients. Si près que vous leur direz ce dont ils ont besoin avant qu''ils s''en rendent compte.', 'Steve Jobs', 'sales'),
  ('q-0579', 'Le prix est ce que vous payez, la valeur est ce que vous obtenez.', 'Warren Buffett', 'finance'),
  ('q-0580', 'À court terme le marché est une machine à voter ; à long terme, c''est une balance.', 'Benjamin Graham', 'finance'),
  ('q-0581', 'Montrez-moi les incitations et je vous montrerai le résultat.', 'Charlie Munger', 'finance'),
  ('q-0582', 'Devenir riche et le rester sont deux compétences complètement différentes.', 'Morgan Housel', 'finance'),
  ('q-0583', 'Ce n''est pas votre salaire qui vous enrichit, c''est vos habitudes de dépense.', 'Charles A. Jaffe', 'finance'),
  ('q-0585', 'Un budget, c''est dire à son argent où aller au lieu de se demander où il est passé.', 'Dave Ramsey', 'finance'),
  ('q-0586', 'Le management c''est bien faire les choses ; le leadership c''est faire les bonnes choses.', 'Peter Drucker', 'leadership'),
  ('q-0587', 'Le leadership, ce n''est pas être aux commandes. C''est prendre soin de ceux dont on a la charge.', 'Simon Sinek', 'leadership'),
  ('q-0589', 'Le leadership est l''art d''obtenir plus que ce que la science du management juge possible.', 'Colin Powell', 'leadership'),
  ('q-0590', 'Prenez soin des gens, du produit et des profits — dans cet ordre.', 'Ben Horowitz', 'leadership'),
  ('q-0591', 'Seuls les paranoïaques survivent.', 'Andy Grove', 'leadership'),
  ('q-0592', 'Embauchez des gens plus intelligents que vous, puis laissez-les faire leur travail.', 'Steve Jobs', 'leadership'),
  ('q-0593', 'Un dirigeant doit dire la vérité, surtout quand elle est mauvaise.', 'Ben Horowitz', 'leadership'),
  ('q-0595', 'Un bon dirigeant assume plus que sa part de responsabilité et prend moins que sa part de mérite.', 'Arnold H. Glasow', 'leadership'),
  ('q-0596', 'Le meilleur chef est celui dont on remarque à peine l''existence.', 'Lao Tseu', 'leadership'),
  ('q-0597', 'L''obstacle à l''action fait avancer l''action. Ce qui se met en travers du chemin devient le chemin.', 'Marc Aurèle', 'mindset'),
  ('q-0598', 'Ce ne sont pas les choses qui troublent les hommes, mais l''opinion qu''ils en ont.', 'Épictète', 'mindset'),
  ('q-0599', 'Vous ne vous élevez pas au niveau de vos objectifs, vous retombez au niveau de vos systèmes.', 'James Clear', 'mindset'),
  ('q-0601', 'La douleur plus la réflexion égale le progrès.', 'Ray Dalio', 'mindset'),
  ('q-0602', 'La concurrence est pour les perdants.', 'Peter Thiel', 'sales'),
  ('q-0603', 'Il vaut mieux avoir cent personnes qui vous adorent que cent mille qui vous trouvent sympathique.', 'Peter Thiel', 'sales'),
  ('q-0604', 'Faites des choses qui ne passent pas à l''échelle.', 'Paul Graham', 'sales'),
  ('q-0605', 'Le logiciel est en train de dévorer le monde.', 'Marc Andreessen', 'sales'),
  ('q-0606', 'Le seul moyen de gagner est d''apprendre plus vite que tout le monde.', 'Eric Ries', 'sales'),
  ('q-0608', 'Il faut commencer par l''expérience client et remonter vers la technologie, jamais l''inverse.', 'Steve Jobs', 'sales'),
  ('q-0609', 'Il faut accepter d''être incompris pendant longtemps.', 'Jeff Bezos', 'sales'),
  ('q-0610', 'Ce qui compte, ce n''est pas ce que vous vendez, c''est le problème que vous résolvez.', 'Clayton Christensen', 'sales'),
  ('q-0611', 'Les gens n''achètent pas une perceuse, ils achètent un trou dans leur mur.', 'Theodore Levitt', 'sales'),
  ('q-0613', 'Un client mécontent est votre meilleure source d''apprentissage.', 'Bill Gates', 'sales'),
  ('q-0614', 'Faites ce que vous faites si bien que les gens auront envie de revenir et d''amener leurs amis.', 'Walt Disney', 'sales'),
  ('q-0615', 'On ne construit pas une réputation sur ce qu''on a l''intention de faire.', 'Henry Ford', 'sales'),
  ('q-0616', 'Si vous avez le temps de flâner, vous avez le temps de nettoyer.', 'Ray Kroc', 'sales'),
  ('q-0617', 'Le doute tue plus de rêves que l''échec ne le fera jamais.', 'Suzy Kassem', 'sales'),
  ('q-0618', 'Créez quelque chose que les gens veulent vraiment. C''est tout.', 'Paul Graham', 'sales'),
  ('q-0620', 'Quelqu''un est assis à l''ombre aujourd''hui parce qu''un autre a planté un arbre il y a longtemps.', 'Warren Buffett', 'finance'),
  ('q-0621', 'Les chaînes de l''habitude sont trop légères pour être senties, jusqu''à ce qu''elles deviennent trop lourdes pour être brisées.', 'Warren Buffett', 'finance'),
  ('q-0622', 'Prévoir la pluie ne compte pas. Construire l''arche, si.', 'Warren Buffett', 'finance'),
  ('q-0623', 'Il faut beaucoup de temps pour devenir riche lentement, et c''est précisément pour cela que peu de gens le font.', 'Charlie Munger', 'finance'),
  ('q-0624', 'Tout ce que je veux savoir, c''est où je vais mourir, comme ça je n''irai jamais.', 'Charlie Munger', 'finance'),
  ('q-0625', 'L''investisseur avisé est un réaliste qui vend aux optimistes et achète aux pessimistes.', 'Benjamin Graham', 'finance'),
  ('q-0626', 'L''ennemi principal de l''investisseur, c''est probablement lui-même.', 'Benjamin Graham', 'finance'),
  ('q-0627', 'Le temps est l''ami des belles entreprises et l''ennemi des médiocres.', 'Warren Buffett', 'finance'),
  ('q-0628', 'Ne me dites pas ce que vous pensez, montrez-moi votre portefeuille.', 'Nassim Nicholas Taleb', 'finance'),
  ('q-0629', 'La richesse, c''est ce que vous ne voyez pas : les voitures non achetées, les sacs non achetés.', 'Morgan Housel', 'finance'),
  ('q-0630', 'Le plus grand dividende que l''argent puisse verser, c''est la maîtrise de votre temps.', 'Morgan Housel', 'finance'),
  ('q-0631', 'Ce ne sont pas les revenus qui font la richesse, c''est l''écart entre ce que vous gagnez et ce que vous dépensez.', 'Thomas J. Stanley', 'finance'),
  ('q-0632', 'Payez-vous en premier.', 'George S. Clason', 'finance'),
  ('q-0633', 'Une partie de tout ce que vous gagnez vous appartient, à vous et à personne d''autre.', 'George S. Clason', 'finance'),
  ('q-0634', 'L''intérêt composé est la force la plus puissante de l''univers financier : celui qui la comprend en profite, celui qui l''ignore la subit.', 'John C. Bogle', 'finance'),
  ('q-0635', 'Le temps passé sur le marché bat le fait de vouloir choisir le bon moment.', 'Peter Lynch', 'finance'),
  ('q-0636', 'Bien plus d''argent a été perdu par des investisseurs à essayer d''anticiper les corrections qu''à en subir.', 'Peter Lynch', 'finance'),
  ('q-0637', 'Il vaut mieux acheter une entreprise formidable à un prix correct qu''une entreprise correcte à un prix formidable.', 'Warren Buffett', 'finance'),
  ('q-0638', 'Ce n''est pas le critique qui compte, ni celui qui montre comment l''homme fort a trébuché. Le mérite revient à celui qui est dans l''arène.', 'Theodore Roosevelt', 'leadership'),
  ('q-0639', 'Faites ce que vous pouvez, avec ce que vous avez, là où vous êtes.', 'Theodore Roosevelt', 'leadership'),
  ('q-0640', 'Le meilleur dirigeant est celui qui a assez de bon sens pour choisir des gens capables, et assez de retenue pour ne pas se mêler de leur travail.', 'Theodore Roosevelt', 'leadership'),
  ('q-0641', 'La difficulté attire l''homme de caractère, car c''est en l''étreignant qu''il se réalise lui-même.', 'Charles de Gaulle', 'leadership'),
  ('q-0642', 'On ne fait rien de grand sans de grands hommes, et ceux-ci le sont pour l''avoir voulu.', 'Charles de Gaulle', 'leadership'),
  ('q-0643', 'Le prix de la grandeur, c''est la responsabilité.', 'Winston Churchill', 'leadership'),
  ('q-0644', 'Un chef est un marchand d''espérance.', 'Napoléon Bonaparte', 'leadership'),
  ('q-0645', 'Ne demandez pas ce que votre pays peut faire pour vous, demandez ce que vous pouvez faire pour votre pays.', 'John F. Kennedy', 'leadership'),
  ('q-0646', 'Le changement est la loi de la vie. Ceux qui ne regardent que le passé ou le présent manqueront à coup sûr l''avenir.', 'John F. Kennedy', 'leadership'),
  ('q-0647', 'Les problèmes du monde ne peuvent être résolus par les sceptiques dont l''horizon se limite aux réalités visibles.', 'John F. Kennedy', 'leadership'),
  ('q-0648', 'L''effort et le courage ne suffisent pas sans but ni direction.', 'John F. Kennedy', 'leadership'),
  ('q-0649', 'Un dirigeant est un homme qui a besoin des autres.', 'Paul Valéry', 'leadership'),
  ('q-0650', 'La qualité d''un dirigeant se mesure aux normes qu''il se fixe à lui-même.', 'Ray Kroc', 'leadership'),
  ('q-0651', 'Les gens ne quittent pas des entreprises, ils quittent des managers.', 'Marcus Buckingham', 'leadership'),
  ('q-0652', 'Mettez d''abord les bonnes personnes dans le bus, ensuite décidez où aller.', 'Jim Collins', 'leadership'),
  ('q-0653', 'Commencez avec la fin en tête.', 'Stephen R. Covey', 'leadership'),
  ('q-0654', 'Cherchez d''abord à comprendre, ensuite à être compris.', 'Stephen R. Covey', 'leadership'),
  ('q-0656', 'Recrutez lentement, licenciez vite.', 'Ray Dalio', 'leadership'),
  ('q-0657', 'Une organisation excellente n''est pas celle où il n''y a pas de problèmes, c''est celle où les problèmes remontent vite.', 'Ray Dalio', 'leadership'),
  ('q-0658', 'La transparence radicale n''est pas confortable, mais elle est efficace.', 'Ray Dalio', 'leadership'),
  ('q-0659', 'Notre culture, c''est la liberté et la responsabilité.', 'Reed Hastings', 'leadership'),
  ('q-0660', 'Le talent dense attire le talent dense.', 'Reed Hastings', 'leadership'),
  ('q-0661', 'L''empathie n''est pas un luxe pour un dirigeant, c''est un outil de travail.', 'Satya Nadella', 'leadership'),
  ('q-0662', 'Notre secteur ne respecte pas la tradition, il ne respecte que l''innovation.', 'Satya Nadella', 'leadership'),
  ('q-0663', 'Le leadership, c''est aussi savoir quand se taire.', 'Indra Nooyi', 'leadership'),
  ('q-0664', 'Supposez toujours la bonne intention chez votre interlocuteur.', 'Indra Nooyi', 'leadership'),
  ('q-0665', 'Si vous voulez aller vite, allez seul. Si vous voulez aller loin, allez ensemble.', 'Proverbe africain', 'leadership'),
  ('q-0667', 'La seule chose que nous devons craindre, c''est la crainte elle-même.', 'Franklin D. Roosevelt', 'leadership'),
  ('q-0668', 'Un bon plan exécuté aujourd''hui vaut mieux qu''un plan parfait exécuté la semaine prochaine.', 'George S. Patton', 'leadership'),
  ('q-0669', 'Ne dites pas aux gens comment faire les choses. Dites-leur quoi faire et laissez-les vous surprendre par leur ingéniosité.', 'George S. Patton', 'leadership'),
  ('q-0670', 'Restez affamés, restez fous.', 'Steve Jobs', 'mindset'),
  ('q-0671', 'On ne peut pas relier les points en regardant devant soi, seulement en regardant en arrière.', 'Steve Jobs', 'mindset'),
  ('q-0672', 'Je n''ai pas échoué. J''ai simplement trouvé dix mille façons qui ne fonctionnent pas.', 'Thomas Edison', 'mindset'),
  ('q-0673', 'La vie se rétrécit ou s''élargit à proportion de notre courage.', 'Anaïs Nin', 'mindset'),
  ('q-0674', 'Vous êtes la moyenne des cinq personnes que vous fréquentez le plus.', 'Jim Rohn', 'mindset'),
  ('q-0675', 'Ne souhaitez pas que ce soit plus facile, souhaitez d''être meilleur.', 'Jim Rohn', 'mindset'),
  ('q-0676', 'Ce que l''esprit peut concevoir et croire, il peut le réaliser.', 'Napoleon Hill', 'mindset'),
  ('q-0677', 'Devenir vaut mieux qu''être.', 'Carol Dweck', 'mindset'),
  ('q-0678', 'Rien dans la vie n''a autant d''importance que vous ne le pensez pendant que vous y pensez.', 'Daniel Kahneman', 'mindset'),
  ('q-0679', 'J''ai raté plus de neuf mille tirs dans ma carrière. C''est pour cela que je réussis.', 'Michael Jordan', 'mindset'),
  ('q-0680', 'On rate cent pour cent des tirs qu''on ne tente pas.', 'Wayne Gretzky', 'mindset'),
  ('q-0681', 'Je détestais chaque minute d''entraînement, mais je me disais : souffre maintenant et vis le reste de ta vie en champion.', 'Muhammad Ali', 'mindset'),
  ('q-0682', 'L''homme qui n''a pas d''imagination n''a pas d''ailes.', 'Muhammad Ali', 'mindset'),
  ('q-0683', 'Le job n''est pas fini.', 'Kobe Bryant', 'mindset'),
  ('q-0684', 'Les gens oublieront ce que vous avez dit et ce que vous avez fait, mais jamais ce que vous leur avez fait ressentir.', 'Maya Angelou', 'mindset'),
  ('q-0685', 'Rien ne fonctionnera si vous ne le faites pas.', 'Maya Angelou', 'mindset'),
  ('q-0686', 'Aujourd''hui est dur, demain sera pire, mais après-demain sera magnifique. La plupart abandonnent le soir du deuxième jour.', 'Jack Ma', 'mindset'),
  ('q-0687', 'Chaque action que vous entreprenez est un vote pour la personne que vous voulez devenir.', 'James Clear', 'mindset'),
  ('q-0688', 'La passion est courante, la persévérance est rare.', 'Angela Duckworth', 'mindset'),
  ('q-0689', 'Le talent, c''est le potentiel. L''effort, c''est ce qui le transforme en résultat.', 'Angela Duckworth', 'mindset'),
  ('q-0691', 'Tu as pouvoir sur ton esprit, pas sur les évènements extérieurs. Comprends cela et tu trouveras la force.', 'Marc Aurèle', 'mindset'),
  ('q-0692', 'Nous souffrons plus souvent en imagination qu''en réalité.', 'Sénèque', 'mindset'),
  ('q-0693', 'Ce n''est pas ce qui t''arrive qui compte, mais la façon dont tu y réagis.', 'Épictète', 'mindset'),
  ('q-0694', 'Ne cherche pas que les évènements arrivent comme tu veux, mais veuille les évènements comme ils arrivent.', 'Épictète', 'mindset'),
  ('q-0695', 'Le premier pas n''emmène pas là où vous voulez aller, mais il vous sort de là où vous êtes.', 'James Clear', 'mindset'),
  ('q-0696', 'Connaître les autres, c''est sagesse. Se connaître soi-même, c''est sagesse supérieure.', 'Lao Tseu', 'mindset'),
  ('q-0697', 'Le succès, c''est de tomber sept fois et de se relever huit.', 'Proverbe japonais', 'mindset'),
  ('q-0699', 'Ce qui ne nous tue pas nous rend plus fort.', 'Friedrich Nietzsche', 'mindset'),
  ('q-0700', 'Celui qui a un pourquoi qui lui tient lieu de but peut supporter presque n''importe quel comment.', 'Friedrich Nietzsche', 'mindset'),
  ('q-0701', 'La plus grande aventure, c''est de vivre la vie de ses rêves.', 'Oprah Winfrey', 'mindset'),
  ('q-0702', 'Transformez vos blessures en sagesse.', 'Oprah Winfrey', 'mindset'),
  ('q-0703', 'Échouer, ce n''est pas ne pas réussir, c''est ne pas essayer.', 'Sara Blakely', 'mindset'),
  ('q-0705', 'La perfection est atteinte non pas lorsqu''il n''y a plus rien à ajouter, mais lorsqu''il n''y a plus rien à retirer.', 'Antoine de Saint-Exupéry', 'mindset'),
  ('q-0707', 'On ne subit pas l''avenir, on le fait.', 'Georges Bernanos', 'mindset'),
  ('q-0709', 'Le pessimiste se plaint du vent, l''optimiste espère qu''il va changer, le réaliste ajuste ses voiles.', 'William Arthur Ward', 'mindset'),
  ('q-0710', 'Le doute est le commencement de la sagesse.', 'Aristote', 'mindset'),
  ('q-0711', 'Nous sommes ce que nous faisons de manière répétée. L''excellence n''est donc pas un acte mais une habitude.', 'Will Durant', 'mindset'),
  ('q-0712', 'Tout le monde savait que c''était impossible. Il est venu un imbécile qui ne le savait pas et qui l''a fait.', 'Marcel Pagnol', 'mindset')
on conflict (id) do nothing;
