-- Revue éditoriale du 30 août 2026 : attributions, traductions, contexte.
--
-- Trois corrections distinctes, toutes constatées citation par citation :
--   1. Retrait de 18 citations fausses, invérifiables ou redondantes (voir la liste plus
--      bas). Les fabrications les mieux documentées : « le secret du changement » attribué
--      à Socrate, en réalité réplique d'un personnage de roman de 1980 ; « si vous mourez
--      pauvre c'est votre erreur » attribué à Bill Gates, issu d'une chaîne de courriels.
--   2. Corrections de traduction qui rétablissent le sens de l'original — la plus nette
--      étant Gretzky, dont le français disait « là où le palet est » au lieu de « là où il
--      était », ce qui supprimait toute l'idée d'anticipation.
--   3. Contexte, source et année renseignés pour 68 citations dont la provenance est
--      vérifiable. Les autres restent nulles : ces champs se vérifient un par un et
--      l'app est faite pour s'en passer.
--
-- Cinq noms d'auteur ont par ailleurs été normalisés : l'app indexe les auteurs par leur
-- libellé exact, donc « Andy Grove » et « Andrew Grove » produisaient deux fiches pour la
-- même personne.

begin;

-- 1. Retraits
delete from public.quotes where id not in (
  'q-0005',
  'q-0006',
  'q-0007',
  'q-0008',
  'q-0009',
  'q-0011',
  'q-0012',
  'q-0013',
  'q-0014',
  'q-0015',
  'q-0016',
  'q-0017',
  'q-0019',
  'q-0020',
  'q-0021',
  'q-0022',
  'q-0023',
  'q-0025',
  'q-0026',
  'q-0029',
  'q-0030',
  'q-0032',
  'q-0033',
  'q-0034',
  'q-0035',
  'q-0037',
  'q-0038',
  'q-0039',
  'q-0040',
  'q-0041',
  'q-0042',
  'q-0043',
  'q-0044',
  'q-0045',
  'q-0046',
  'q-0047',
  'q-0048',
  'q-0050',
  'q-0051',
  'q-0052',
  'q-0053',
  'q-0054',
  'q-0055',
  'q-0057',
  'q-0058',
  'q-0059',
  'q-0060',
  'q-0061',
  'q-0062',
  'q-0063',
  'q-0065',
  'q-0069',
  'q-0070',
  'q-0072',
  'q-0073',
  'q-0074',
  'q-0075',
  'q-0076',
  'q-0077',
  'q-0079',
  'q-0080',
  'q-0081',
  'q-0085',
  'q-0086',
  'q-0087',
  'q-0088',
  'q-0089',
  'q-0090',
  'q-0094',
  'q-0097',
  'q-0098',
  'q-0099',
  'q-0100',
  'q-0101',
  'q-0102',
  'q-0103',
  'q-0105',
  'q-0106',
  'q-0107',
  'q-0108',
  'q-0110',
  'q-0113',
  'q-0115',
  'q-0116',
  'q-0117',
  'q-0118',
  'q-0120',
  'q-0121',
  'q-0122',
  'q-0123',
  'q-0124',
  'q-0125',
  'q-0126',
  'q-0127',
  'q-0129',
  'q-0130',
  'q-0131',
  'q-0132',
  'q-0133',
  'q-0134',
  'q-0135',
  'q-0136',
  'q-0137',
  'q-0138',
  'q-0139',
  'q-0140',
  'q-0141',
  'q-0142',
  'q-0143',
  'q-0145',
  'q-0146',
  'q-0147',
  'q-0148',
  'q-0151',
  'q-0152',
  'q-0153',
  'q-0154',
  'q-0155',
  'q-0156',
  'q-0157',
  'q-0158',
  'q-0161',
  'q-0162',
  'q-0164',
  'q-0165',
  'q-0166',
  'q-0168',
  'q-0170',
  'q-0172',
  'q-0173',
  'q-0174',
  'q-0176',
  'q-0177',
  'q-0178',
  'q-0179',
  'q-0180',
  'q-0181',
  'q-0182',
  'q-0183',
  'q-0184',
  'q-0185',
  'q-0187',
  'q-0188',
  'q-0191',
  'q-0193',
  'q-0195',
  'q-0196',
  'q-0197',
  'q-0199',
  'q-0200',
  'q-0201',
  'q-0202',
  'q-0203',
  'q-0205',
  'q-0206',
  'q-0207',
  'q-0208',
  'q-0209',
  'q-0210',
  'q-0211',
  'q-0213',
  'q-0214',
  'q-0221',
  'q-0224',
  'q-0225',
  'q-0226',
  'q-0227',
  'q-0228',
  'q-0229',
  'q-0230',
  'q-0231',
  'q-0232',
  'q-0233',
  'q-0234',
  'q-0235',
  'q-0236',
  'q-0237',
  'q-0239',
  'q-0244',
  'q-0245',
  'q-0247',
  'q-0248',
  'q-0249',
  'q-0250',
  'q-0251',
  'q-0252',
  'q-0253',
  'q-0254',
  'q-0256',
  'q-0257',
  'q-0258',
  'q-0259',
  'q-0260',
  'q-0261',
  'q-0262',
  'q-0263',
  'q-0264',
  'q-0265',
  'q-0266',
  'q-0267',
  'q-0268',
  'q-0269',
  'q-0270',
  'q-0271',
  'q-0272',
  'q-0273',
  'q-0274',
  'q-0275',
  'q-0276',
  'q-0277',
  'q-0278',
  'q-0279',
  'q-0280',
  'q-0281',
  'q-0282',
  'q-0283',
  'q-0284',
  'q-0285',
  'q-0287',
  'q-0289',
  'q-0290',
  'q-0292',
  'q-0293',
  'q-0294',
  'q-0295',
  'q-0296',
  'q-0297',
  'q-0299',
  'q-0300',
  'q-0301',
  'q-0302',
  'q-0303',
  'q-0304',
  'q-0305',
  'q-0308',
  'q-0312',
  'q-0314',
  'q-0316',
  'q-0317',
  'q-0318',
  'q-0319',
  'q-0320',
  'q-0321',
  'q-0322',
  'q-0323',
  'q-0324',
  'q-0325',
  'q-0326',
  'q-0327',
  'q-0328',
  'q-0329',
  'q-0330',
  'q-0331',
  'q-0332',
  'q-0333',
  'q-0334',
  'q-0335',
  'q-0336',
  'q-0337',
  'q-0338',
  'q-0339',
  'q-0340',
  'q-0341',
  'q-0342',
  'q-0344',
  'q-0345',
  'q-0346',
  'q-0347',
  'q-0348',
  'q-0349',
  'q-0351',
  'q-0352',
  'q-0353',
  'q-0354',
  'q-0356',
  'q-0357',
  'q-0358',
  'q-0359',
  'q-0360',
  'q-0361',
  'q-0362',
  'q-0363',
  'q-0364',
  'q-0365',
  'q-0366',
  'q-0367',
  'q-0368',
  'q-0369',
  'q-0371',
  'q-0372',
  'q-0373',
  'q-0374',
  'q-0375',
  'q-0378',
  'q-0379',
  'q-0380',
  'q-0382',
  'q-0383',
  'q-0384',
  'q-0385',
  'q-0386',
  'q-0389',
  'q-0390',
  'q-0392',
  'q-0393',
  'q-0394',
  'q-0395',
  'q-0398',
  'q-0399',
  'q-0400',
  'q-0401',
  'q-0402',
  'q-0403',
  'q-0404',
  'q-0405',
  'q-0406',
  'q-0407',
  'q-0408',
  'q-0409',
  'q-0410',
  'q-0411',
  'q-0412',
  'q-0413',
  'q-0414',
  'q-0415',
  'q-0416',
  'q-0417',
  'q-0419',
  'q-0420',
  'q-0425',
  'q-0426',
  'q-0427',
  'q-0429',
  'q-0431',
  'q-0434',
  'q-0436',
  'q-0437',
  'q-0439',
  'q-0440',
  'q-0442',
  'q-0443',
  'q-0444',
  'q-0451',
  'q-0455',
  'q-0456',
  'q-0457',
  'q-0460',
  'q-0461',
  'q-0462',
  'q-0464',
  'q-0465',
  'q-0466',
  'q-0467',
  'q-0468',
  'q-0470',
  'q-0471',
  'q-0473',
  'q-0474',
  'q-0478',
  'q-0482',
  'q-0483',
  'q-0485',
  'q-0487',
  'q-0488',
  'q-0489',
  'q-0490',
  'q-0491',
  'q-0493',
  'q-0494',
  'q-0495',
  'q-0496',
  'q-0497',
  'q-0498',
  'q-0499',
  'q-0500',
  'q-0503',
  'q-0504',
  'q-0507',
  'q-0508',
  'q-0509',
  'q-0510',
  'q-0511',
  'q-0512',
  'q-0513',
  'q-0514',
  'q-0516',
  'q-0518',
  'q-0519',
  'q-0520',
  'q-0522',
  'q-0524',
  'q-0525',
  'q-0526',
  'q-0527',
  'q-0529',
  'q-0531',
  'q-0532',
  'q-0534',
  'q-0535',
  'q-0536',
  'q-0537',
  'q-0539',
  'q-0540',
  'q-0541',
  'q-0544',
  'q-0545',
  'q-0546',
  'q-0547',
  'q-0548',
  'q-0549',
  'q-0550',
  'q-0551',
  'q-0552',
  'q-0553',
  'q-0555',
  'q-0556',
  'q-0557',
  'q-0558',
  'q-0559',
  'q-0560',
  'q-0561',
  'q-0562',
  'q-0563',
  'q-0564',
  'q-0565',
  'q-0566',
  'q-0567',
  'q-0568',
  'q-0569',
  'q-0570',
  'q-0571',
  'q-0572',
  'q-0573',
  'q-0574',
  'q-0575',
  'q-0576',
  'q-0577',
  'q-0578',
  'q-0579',
  'q-0580',
  'q-0581',
  'q-0582',
  'q-0583',
  'q-0585',
  'q-0586',
  'q-0587',
  'q-0589',
  'q-0590',
  'q-0591',
  'q-0592',
  'q-0593',
  'q-0595',
  'q-0596',
  'q-0597',
  'q-0598',
  'q-0599',
  'q-0601',
  'q-0602',
  'q-0603',
  'q-0604',
  'q-0605',
  'q-0606',
  'q-0608',
  'q-0609',
  'q-0610',
  'q-0611',
  'q-0614',
  'q-0615',
  'q-0616',
  'q-0617',
  'q-0618',
  'q-0620',
  'q-0621',
  'q-0623',
  'q-0624',
  'q-0625',
  'q-0626',
  'q-0627',
  'q-0628',
  'q-0629',
  'q-0630',
  'q-0631',
  'q-0632',
  'q-0633',
  'q-0635',
  'q-0636',
  'q-0637',
  'q-0638',
  'q-0639',
  'q-0640',
  'q-0641',
  'q-0642',
  'q-0643',
  'q-0644',
  'q-0645',
  'q-0646',
  'q-0647',
  'q-0648',
  'q-0649',
  'q-0650',
  'q-0651',
  'q-0652',
  'q-0653',
  'q-0654',
  'q-0656',
  'q-0657',
  'q-0658',
  'q-0659',
  'q-0660',
  'q-0661',
  'q-0662',
  'q-0663',
  'q-0664',
  'q-0665',
  'q-0667',
  'q-0668',
  'q-0669',
  'q-0670',
  'q-0671',
  'q-0672',
  'q-0673',
  'q-0674',
  'q-0675',
  'q-0676',
  'q-0677',
  'q-0678',
  'q-0679',
  'q-0680',
  'q-0681',
  'q-0682',
  'q-0683',
  'q-0684',
  'q-0685',
  'q-0686',
  'q-0687',
  'q-0688',
  'q-0689',
  'q-0691',
  'q-0692',
  'q-0693',
  'q-0694',
  'q-0695',
  'q-0696',
  'q-0697',
  'q-0699',
  'q-0700',
  'q-0701',
  'q-0702',
  'q-0703',
  'q-0705',
  'q-0707',
  'q-0709',
  'q-0710',
  'q-0711',
  'q-0712'
);

-- 2. Textes, auteurs, contexte, source, année
insert into public.quotes (id, text, author, category, context, source, year) values
  ('q-0005', 'Quand vous êtes dans le sens contraire du courant et que vous nagez vite, vous reculez moins que les autres.', 'Bernard Tapie', 'mindset', null, null, null),
  ('q-0006', 'La réussite, c''est un peu de talent, beaucoup de travail et surtout une passion dévorante.', 'Bernard Tapie', 'mindset', null, null, null),
  ('q-0007', 'Seul un poisson mort navigue dans le sens du courant.', 'Bernard Arnault', 'mindset', null, null, null),
  ('q-0008', 'Un bon produit peut durer éternellement.', 'Bernard Arnault', 'mindset', null, null, null),
  ('q-0009', 'Si vous contrôlez votre distribution, vous contrôlez votre image.', 'Bernard Arnault', 'leadership', null, null, null),
  ('q-0011', 'La seule façon de faire du bon travail est d''aimer ce que vous faites.', 'Steve Jobs', 'mindset', 'Extrait du passage où Jobs raconte avoir fondé Apple, en être parti, puis y être revenu — et conclut que seule la passion permet de continuer face à l''échec.', 'Discours de remise des diplômes, Université Stanford', 2005),
  ('q-0012', 'L''innovation distingue un leader d''un suiveur.', 'Steve Jobs', 'leadership', null, null, null),
  ('q-0013', 'Votre temps est limité, ne le gaspillez pas en vivant la vie de quelqu''un d''autre.', 'Steve Jobs', 'mindset', 'Dans la troisième partie du discours, consacrée à sa maladie et à la mort : Jobs y explique que la conscience du temps limité doit pousser à suivre son propre chemin plutôt que les attentes des autres.', 'Discours de remise des diplômes, Université Stanford', 2005),
  ('q-0014', 'Qu''est-ce qu''une entreprise ? C''est simplement une idée qui améliore la vie de quelqu''un d''autre.', 'Richard Branson', 'leadership', null, null, null),
  ('q-0015', 'Écoutez plus que vous parlez. Personne n''a rien appris en s''entendant parler.', 'Richard Branson', 'leadership', null, null, null),
  ('q-0016', 'Seul un imbécile ne change jamais d''avis.', 'Richard Branson', 'mindset', null, null, null),
  ('q-0017', 'L''opportunité se situe à l''endroit où se trouvent les réclamations et les plaintes.', 'Jack Ma', 'mindset', null, null, null),
  ('q-0019', 'L''échec est simplement l''opportunité de recommencer, cette fois de manière plus pertinente.', 'Henry Ford', 'mindset', null, null, null),
  ('q-0020', 'Prenez mes idées, j''en aurai d''autres.', 'Coco Chanel', 'mindset', null, null, null),
  ('q-0021', 'Prudence n''est que l''euphémisme de peur.', 'Jules Renard', 'mindset', null, null, null),
  ('q-0022', 'La peur bloque la compréhension intelligente de la vie.', 'Jiddu Krishnamurti', 'mindset', null, null, null),
  ('q-0023', 'J''ai appris que le courage n''est pas l''absence de peur, mais la capacité de la vaincre.', 'Nelson Mandela', 'mindset', null, null, null),
  ('q-0025', 'Le seul endroit où le succès vient avant le travail, c''est dans le dictionnaire.', 'Vidal Sassoon', 'mindset', null, null, null),
  ('q-0026', 'Les gagnants trouvent des moyens, les perdants des excuses.', 'Franklin D. Roosevelt', 'mindset', null, null, null),
  ('q-0029', 'Un pessimiste voit la difficulté dans chaque opportunité. Un optimiste voit une opportunité dans chaque difficulté.', 'Winston Churchill', 'mindset', null, null, null),
  ('q-0030', 'Ne cherchez pas d''ascenseur, il n''y en a pas : les entrepreneurs prennent toujours l''escalier !', 'Frédéric Mazzella', 'mindset', null, null, null),
  ('q-0032', 'Le capitalisme est un pari sur le mouvement : c''est de là que vient le progrès.', 'Alain Minc', 'finance', null, null, null),
  ('q-0033', 'La victoire appartient à celui qui a la persévérance la plus longue.', 'Napoléon Bonaparte', 'mindset', null, null, null),
  ('q-0034', 'Toutes les choses semblent réalisables par la volonté et le courage.', 'Napoléon Bonaparte', 'mindset', null, null, null),
  ('q-0035', 'Se concentrer sur le client rend une entreprise plus résiliente.', 'Jeff Bezos', 'sales', null, null, null),
  ('q-0037', 'Votre marque est ce que les gens disent de vous lorsque vous n''êtes pas dans la pièce.', 'Jeff Bezos', 'sales', null, null, null),
  ('q-0038', 'Si vous ne voulez jamais être critiqué, ne faites rien de nouveau.', 'Jeff Bezos', 'mindset', null, null, null),
  ('q-0039', 'Observez les clients, pas les concurrents.', 'Jeff Bezos', 'sales', null, null, null),
  ('q-0040', 'Si vous voulez être inventif, vous devez être prêt à échouer.', 'Jeff Bezos', 'mindset', null, null, null),
  ('q-0041', 'L''échec fait partie intégrante de l''invention.', 'Jeff Bezos', 'mindset', null, null, null),
  ('q-0042', 'Nous sommes têtus sur la vision. Nous sommes flexibles sur les détails.', 'Jeff Bezos', 'leadership', null, null, null),
  ('q-0043', 'L''échec est une option. Si les choses n''échouent pas, vous n''innovez pas assez.', 'Elon Musk', 'mindset', null, null, null),
  ('q-0044', 'La persévérance est très importante. N''abandonnez jamais à moins d''y être obligé.', 'Elon Musk', 'mindset', null, null, null),
  ('q-0045', 'Beaucoup de choses sont improbables, seules quelques-unes sont impossibles.', 'Elon Musk', 'mindset', null, null, null),
  ('q-0046', 'Si les règles vous empêchent de progresser, battez-vous pour les changer.', 'Elon Musk', 'mindset', null, null, null),
  ('q-0047', 'Vous devez être assez motivé pour y arriver. Sinon, vous vous rendrez simplement malheureux.', 'Elon Musk', 'mindset', null, null, null),
  ('q-0048', 'Lorsque quelque chose est suffisamment important, vous le faites même si les chances ne sont pas en votre faveur.', 'Elon Musk', 'mindset', null, null, null),
  ('q-0050', 'Se réunir est un début ; rester ensemble est un progrès ; travailler ensemble est la réussite.', 'Henry Ford', 'leadership', null, null, null),
  ('q-0051', 'Quand tout semble être contre vous, souvenez-vous que l''avion décolle face au vent.', 'Henry Ford', 'mindset', null, null, null),
  ('q-0052', 'Ce n''est pas l''employeur qui paie les salaires, mais le client.', 'Henry Ford', 'sales', null, null, null),
  ('q-0053', 'Les deux choses les plus importantes n''apparaissent pas au bilan : sa réputation et ses hommes.', 'Henry Ford', 'leadership', null, null, null),
  ('q-0054', 'La qualité signifie faire les choses correctement quand personne ne regarde.', 'Henry Ford', 'mindset', null, null, null),
  ('q-0055', 'Les obstacles sont ces choses effrayantes que vous voyez quand vous détournez les yeux de votre objectif.', 'Henry Ford', 'mindset', null, null, null),
  ('q-0057', 'Il faut 20 ans pour bâtir une réputation et cinq minutes pour l''anéantir.', 'Warren Buffett', 'finance', null, null, null),
  ('q-0058', 'Le risque provient de ne pas savoir ce que l''on fait.', 'Warren Buffett', 'finance', null, null, null),
  ('q-0059', 'Achetez seulement des choses que vous seriez parfaitement heureux de posséder si le marché s''effondrait pendant dix ans.', 'Warren Buffett', 'finance', 'Buffett y explique qu''il ne faut acheter que des entreprises dont on accepterait de ne plus jamais voir le cours, preuve qu''on les détient pour ce qu''elles produisent et non pour les revendre.', 'Lettre aux actionnaires de Berkshire Hathaway', 1996),
  ('q-0060', 'Notre horizon d''investissement préféré est : pour toujours.', 'Warren Buffett', 'finance', 'Formulé en commentant l''achat de Coca-Cola : Buffett y distingue les investisseurs qui gardent leurs meilleures entreprises de ceux qui s''en séparent dès qu''elles réussissent.', 'Lettre aux actionnaires de Berkshire Hathaway', 1988),
  ('q-0061', 'La bourse est un moyen de transférer l''argent des impatients vers les patients.', 'Warren Buffett', 'finance', null, null, null),
  ('q-0062', 'Le meilleur investissement que vous puissiez faire, c''est de miser sur vos propres capacités.', 'Warren Buffett', 'finance', null, null, null),
  ('q-0063', 'Tous nos rêves peuvent devenir réalité si nous avons le courage de les poursuivre.', 'Walt Disney', 'mindset', null, null, null),
  ('q-0065', 'La manière de commencer est d''arrêter de parler et de commencer à faire.', 'Walt Disney', 'mindset', null, null, null),
  ('q-0069', 'La patience est un élément clé de la réussite.', 'Bill Gates', 'mindset', null, 'La Route du futur', 1995),
  ('q-0070', 'Le succès est un mauvais professeur. Il pousse les gens intelligents à croire qu''ils sont infaillibles.', 'Bill Gates', 'mindset', null, 'La Route du futur', 1995),
  ('q-0072', 'Pour gagner gros, il faut parfois prendre de gros risques.', 'Bill Gates', 'finance', null, null, null),
  ('q-0073', 'Célébrer le succès, c''est bien, mais il est plus important de tirer les leçons de l''échec.', 'Bill Gates', 'mindset', null, null, null),
  ('q-0074', 'Le plus grand risque est de ne prendre aucun risque.', 'Mark Zuckerberg', 'mindset', null, null, null),
  ('q-0075', 'Si vous ne cassez rien, c''est que vous n''avancez pas assez vite.', 'Mark Zuckerberg', 'mindset', null, null, null),
  ('q-0076', 'La chose la plus importante est de garder votre équipe aussi petite que possible.', 'Mark Zuckerberg', 'leadership', null, null, null),
  ('q-0077', 'Mon objectif n''a jamais été de créer une entreprise, mais de bâtir quelque chose susceptible de changer le monde.', 'Mark Zuckerberg', 'leadership', null, null, null),
  ('q-0079', 'L''échec est un excellent enseignant et chaque erreur a une leçon à offrir.', 'Oprah Winfrey', 'mindset', null, null, null),
  ('q-0080', 'Entourez-vous seulement de personnes qui vont vous élever plus haut.', 'Oprah Winfrey', 'mindset', null, null, null),
  ('q-0081', 'Vous ne devenez pas ce que vous voulez, vous devenez ce que vous croyez.', 'Oprah Winfrey', 'mindset', null, null, null),
  ('q-0085', 'Celui qui n''a pas d''objectifs ne risque pas de les atteindre.', 'Sun Tzu', 'mindset', null, null, null),
  ('q-0086', 'Le bon général a gagné la bataille avant de l''engager.', 'Sun Tzu', 'leadership', null, 'L''Art de la guerre, chapitre IV', null),
  ('q-0087', 'Un grand dirigeant commande par l''exemple et non par la force.', 'Sun Tzu', 'leadership', null, null, null),
  ('q-0088', 'Connais l''adversaire et surtout connais-toi toi-même et tu seras invincible.', 'Sun Tzu', 'mindset', null, 'L''Art de la guerre, chapitre III', null),
  ('q-0089', 'Le commencement est beaucoup plus que la moitié de l''objectif.', 'Aristote', 'mindset', null, null, null),
  ('q-0090', 'C''est par l''expérience que la science et l''art font leur progrès.', 'Aristote', 'mindset', null, null, null),
  ('q-0094', 'Faites le premier pas sur le chemin de la foi. Vous n''avez pas à le parcourir entièrement, juste à faire le premier pas.', 'Martin Luther King', 'mindset', null, null, null),
  ('q-0097', 'Tout ce que tu feras sera dérisoire, mais il est essentiel que tu le fasses.', 'Mahatma Gandhi', 'mindset', null, null, null),
  ('q-0098', 'Je ne crains pas l''homme qui a pratiqué 10 000 coups une fois, mais celui qui a pratiqué un coup 10 000 fois.', 'Bruce Lee', 'mindset', null, null, null),
  ('q-0099', 'Connaître ne suffit pas, il faut savoir appliquer. La volonté ne suffit pas, il faut savoir agir.', 'Bruce Lee', 'mindset', null, null, null),
  ('q-0100', 'Ne crains pas l''échec. Ce n''est pas l''échec, mais le manque d''ambition qui est un crime.', 'Bruce Lee', 'mindset', null, null, null),
  ('q-0101', 'Il n''y a pas de limites. Il n''y a que des paliers, et tu ne dois pas t''y arrêter.', 'Bruce Lee', 'mindset', null, null, null),
  ('q-0102', 'C''est dur d''échouer, mais c''est pire de n''avoir jamais essayé de réussir.', 'Theodore Roosevelt', 'mindset', null, null, null),
  ('q-0103', 'Le seul homme à ne jamais faire d''erreurs est celui qui ne fait rien.', 'Theodore Roosevelt', 'mindset', null, null, null),
  ('q-0105', 'Parlez doucement, et tenez un gros bâton, vous irez loin.', 'Theodore Roosevelt', 'leadership', null, null, null),
  ('q-0106', 'N''ayez pas peur d''échouer. Ayez peur de ne pas essayer.', 'Michael Jordan', 'mindset', null, null, null),
  ('q-0107', 'Je peux accepter l''échec, tout le monde échoue dans quelque chose. Mais je ne peux pas accepter de ne pas essayer.', 'Michael Jordan', 'mindset', null, null, null),
  ('q-0108', 'Plus je me prépare, plus j''ai de chance.', 'Michael Jordan', 'mindset', null, null, null),
  ('q-0110', 'Le talent fait gagner les matches, mais le travail d''équipe et l''intelligence font gagner des tournois.', 'Michael Jordan', 'leadership', null, null, null),
  ('q-0113', 'Il n''y a qu''une réponse à la défaite, et c''est la victoire.', 'Winston Churchill', 'mindset', null, null, null),
  ('q-0115', 'Pour s''améliorer, il faut changer. Donc, pour être parfait, il faut avoir changé souvent.', 'Winston Churchill', 'mindset', null, null, null),
  ('q-0116', 'Celui qui déplace la montagne, c''est celui qui commence à enlever les petites pierres.', 'Confucius', 'mindset', null, null, null),
  ('q-0117', 'Celui qui ne progresse pas chaque jour, recule chaque jour.', 'Confucius', 'mindset', null, null, null),
  ('q-0118', 'Un homme est grand non pas parce qu''il n''a pas échoué ; un homme est grand parce que l''échec ne l''a pas arrêté.', 'Confucius', 'mindset', null, null, null),
  ('q-0120', 'Ne vous souciez pas de n''être pas remarqué ; cherchez plutôt à faire quelque chose de remarquable.', 'Confucius', 'mindset', null, null, null),
  ('q-0121', 'Exige beaucoup de toi-même et attends peu des autres.', 'Confucius', 'mindset', null, null, null),
  ('q-0122', 'Dans les affaires, les grandes choses ne sont jamais faites par une seule personne.', 'Steve Jobs', 'leadership', null, null, null),
  ('q-0123', 'Les gens qui sont assez fous pour penser qu''ils peuvent changer le monde sont ceux qui le font.', 'Steve Jobs', 'mindset', 'Signature de la campagne « Think Different » qui a marqué le retour de Jobs à la tête d''Apple — sa rédaction exacte est disputée entre lui et l''agence TBWA\Chiat\Day, mais la phrase reste associée à son retour.', 'Campagne publicitaire « Think Different », Apple', 1997),
  ('q-0124', 'La simplicité est la sophistication ultime.', 'Steve Jobs', 'mindset', 'Apparue sur une brochure du premier Apple II avant de devenir une formule répétée par Jobs pendant des décennies. Elle est aussi, à tort, très souvent attribuée à Léonard de Vinci — aucune trace de cette phrase n''existe dans ses écrits.', 'Brochure publicitaire de l''Apple II, Apple', 1977),
  ('q-0125', 'Je suis convaincu qu''environ la moitié de ce qui sépare les entrepreneurs qui réussissent de ceux qui échouent, c''est la pure persévérance.', 'Steve Jobs', 'mindset', null, null, null),
  ('q-0126', 'Innover, c''est savoir abandonner des milliers de bonnes idées.', 'Steve Jobs', 'mindset', null, null, null),
  ('q-0127', 'Cela n''a aucun sens d''embaucher des gens intelligents et de leur dire quoi faire.', 'Steve Jobs', 'leadership', 'Sa dernière interview publique, où il détaille sa philosophie du management : diriger par les idées plutôt que par la hiérarchie.', 'Conférence D8, entretien avec Walt Mossberg et Kara Swisher', 2010),
  ('q-0129', 'Ne quittez jamais les flux de trésorerie des yeux, car c''est le sang de l''entreprise.', 'Richard Branson', 'finance', null, null, null),
  ('q-0130', 'La complexité est votre ennemie. N''importe quel imbécile peut compliquer quelque chose.', 'Richard Branson', 'mindset', null, null, null),
  ('q-0131', 'Les opportunités, c''est comme les autobus, il y en a toujours un autre qui arrive.', 'Richard Branson', 'mindset', null, null, null),
  ('q-0132', 'Si vous vous occupez de votre personnel, ils s''occuperont de vos clients.', 'Richard Branson', 'sales', null, null, null),
  ('q-0133', 'Vous devez prendre des risques si vous voulez réussir.', 'Richard Branson', 'mindset', null, null, null),
  ('q-0134', 'Parfois, la décision la plus risquée que vous puissiez prendre est de ne rien faire.', 'Richard Branson', 'mindset', null, null, null),
  ('q-0135', 'Lancer une entreprise, c''est résoudre des problèmes avec succès.', 'Richard Branson', 'leadership', null, null, null),
  ('q-0136', 'Réussir en affaires, c''est avant tout créer des liens.', 'Richard Branson', 'sales', null, null, null),
  ('q-0137', 'Le bonheur est l''ingrédient secret des entreprises prospères.', 'Richard Branson', 'leadership', null, null, null),
  ('q-0138', 'Ce qu''on obtient en atteignant nos objectifs n''est pas aussi important que ce que l''on devient en les atteignant.', 'Zig Ziglar', 'mindset', null, null, null),
  ('q-0139', 'La pire décision de toutes est celle que l''on n''a pas prise.', 'Zig Ziglar', 'mindset', null, null, null),
  ('q-0140', 'La meilleure arme de persuasion que tu possèdes dans ton arsenal est l''intégrité.', 'Zig Ziglar', 'sales', null, null, null),
  ('q-0141', 'Si l''échec vous apprend quelque chose, vous n''êtes pas vraiment perdant.', 'Zig Ziglar', 'mindset', null, null, null),
  ('q-0142', 'Gagner n''est pas tout, mais l''effort qu''il faut fournir l''est.', 'Zig Ziglar', 'mindset', null, null, null),
  ('q-0143', 'Plus vous aidez les gens à obtenir ce qu''ils désirent, plus vous avez de succès.', 'Zig Ziglar', 'sales', null, null, null),
  ('q-0145', 'Le succès ne s''explique pas. L''échec ne s''excuse pas.', 'Napoleon Hill', 'mindset', null, null, null),
  ('q-0146', 'Chaque difficulté porte en elle le germe d''un avantage équivalent ou supérieur.', 'Napoleon Hill', 'mindset', null, null, null),
  ('q-0147', 'Les opportunités apparaissent le plus souvent sous la forme de malchance ou d''échec temporaire.', 'Napoleon Hill', 'mindset', null, null, null),
  ('q-0148', 'Le monde a l''habitude de faire de la place à l''homme dont les paroles et les actions montrent qu''il sait où il va.', 'Napoleon Hill', 'mindset', null, null, null),
  ('q-0151', 'S''il y a un secret à l''efficacité, c''est la concentration.', 'Peter Drucker', 'mindset', null, null, null),
  ('q-0152', 'Le temps est le capital le plus rare, et si on ne sait pas le gérer, alors on ne peut rien gérer d''autre.', 'Peter Drucker', 'leadership', null, null, null),
  ('q-0153', 'L''entreprise n''a que deux fonctions de base : commercialiser et innover.', 'Peter Drucker', 'leadership', null, null, null),
  ('q-0154', 'On obtient des résultats en exploitant des opportunités, non en résolvant des problèmes.', 'Peter Drucker', 'mindset', null, null, null),
  ('q-0155', 'Il n''y a pas « un » caractère d''entrepreneur. Mais il faut « du » caractère pour l''être.', 'Peter Drucker', 'mindset', null, null, null),
  ('q-0156', 'Pour être irremplaçable, il faut être différente.', 'Coco Chanel', 'mindset', null, null, null),
  ('q-0157', 'La mode se démode, le style jamais.', 'Coco Chanel', 'mindset', null, null, null),
  ('q-0158', 'Ma vie ne me plaisait pas, alors j''ai créé ma vie.', 'Coco Chanel', 'mindset', null, null, null),
  ('q-0161', 'Un investissement dans le savoir paie toujours les meilleurs intérêts.', 'Benjamin Franklin', 'finance', null, null, null),
  ('q-0162', 'Le temps, c''est de l''argent.', 'Benjamin Franklin', 'finance', null, 'Advice to a Young Tradesman', 1748),
  ('q-0164', 'Si vous ne parvenez pas à planifier, vous prévoyez d''échouer !', 'Benjamin Franklin', 'mindset', null, null, null),
  ('q-0165', 'Ne remettez pas au lendemain ce que vous pouvez faire le jour même.', 'Benjamin Franklin', 'mindset', null, 'L''Almanach du pauvre Richard', null),
  ('q-0166', 'La paresse chemine si lentement que la pauvreté la rattrape.', 'Benjamin Franklin', 'finance', null, 'L''Almanach du pauvre Richard', null),
  ('q-0168', 'Dans 20 ans, vous serez plus déçu par les choses que vous n''avez pas faites que par celles que vous avez faites.', 'H. Jackson Brown Jr.', 'mindset', null, null, null),
  ('q-0170', 'Chaque fois que vous vous trouvez du côté de la majorité, il est temps de faire une pause et de réfléchir.', 'Mark Twain', 'mindset', null, 'Carnets', null),
  ('q-0172', 'Trop de publicité tue la publicité.', 'Jacques Séguéla', 'sales', null, null, null),
  ('q-0173', 'Tout homme qui meurt riche meurt déshonoré.', 'Andrew Carnegie', 'finance', 'Carnegie a donné la quasi-totalité de sa fortune de son vivant, finançant plus de 2 500 bibliothèques publiques.', 'L''Évangile de la richesse', 1889),
  ('q-0174', 'Aucun homme ne devient riche à moins qu''il enrichisse autrui.', 'Andrew Carnegie', 'finance', null, null, null),
  ('q-0176', 'Faites votre devoir et un peu plus encore, et l''avenir prendra soin de lui-même.', 'Andrew Carnegie', 'mindset', null, null, null),
  ('q-0177', 'Concentrez vos énergies, vos pensées et votre capital.', 'Andrew Carnegie', 'finance', null, null, null),
  ('q-0178', 'Ceux qui réussissent sont des hommes qui ont choisi une ligne de conduite et qui s''y tiennent.', 'Andrew Carnegie', 'mindset', null, null, null),
  ('q-0179', 'Ce n''est pas parce que les choses sont difficiles que nous n''osons pas, c''est parce que nous n''osons pas qu''elles sont difficiles.', 'Sénèque', 'mindset', null, 'Lettres à Lucilius, lettre 104', null),
  ('q-0180', 'Il n''est pas de vent favorable pour celui qui ne sait pas où il va.', 'Sénèque', 'mindset', null, 'Lettres à Lucilius, lettre 71', null),
  ('q-0181', 'C''est par l''épreuve du feu qu''on reconnaît l''or pur. C''est par les épreuves qu''on reconnaît l''homme de cœur.', 'Sénèque', 'mindset', null, null, null),
  ('q-0182', 'Le plus grand obstacle à la vie est l''attente, qui espère demain et néglige aujourd''hui.', 'Sénèque', 'mindset', 'Sénèque y répond à ceux qui se plaignent de la brièveté de la vie : elle est assez longue, c''est l''usage qu''on en fait qui la gaspille.', 'De la brièveté de la vie', null),
  ('q-0183', 'À force de remettre à plus tard, la vie nous dépasse.', 'Sénèque', 'mindset', null, 'Lettres à Lucilius, lettre 1', null),
  ('q-0184', 'C''est pendant l''orage qu''on connaît le pilote.', 'Sénèque', 'mindset', null, null, null),
  ('q-0185', 'Un voyage de mille lieues commence toujours par un premier pas.', 'Lao Tseu', 'mindset', null, 'Tao Tö King, chapitre 64', null),
  ('q-0187', 'Qui triomphe de lui-même possède la force.', 'Lao Tseu', 'mindset', null, 'Tao Tö King, chapitre 33', null),
  ('q-0188', 'Tout ce que je sais, c''est que je ne sais rien.', 'Socrate', 'mindset', null, null, null),
  ('q-0191', 'Une vie sans examen ne vaut pas la peine d''être vécue.', 'Socrate', 'mindset', 'Ce que Socrate répond à ses juges qui lui proposent l''exil plutôt que la mort : une vie sauvée au prix de renoncer à examiner ses idées ne l''intéresse pas.', 'Platon, Apologie de Socrate', null),
  ('q-0193', 'Sois comme un promontoire contre lequel les flots viennent sans cesse se briser.', 'Marc Aurèle', 'mindset', null, 'Pensées pour moi-même, livre IV', null),
  ('q-0195', 'Avoir du courage ne veut pas dire que nous n''avons pas peur, mais que nous affrontons nos peurs.', 'Maya Angelou', 'mindset', null, null, null),
  ('q-0196', 'Vous ferez face à de nombreuses défaites dans votre vie, mais ne vous laissez jamais vaincre.', 'Maya Angelou', 'mindset', null, null, null),
  ('q-0197', 'Faites de votre mieux jusqu''à ce que vous sachiez faire mieux. Et quand vous saurez, faites mieux.', 'Maya Angelou', 'mindset', null, null, null),
  ('q-0199', 'Aussi dur que tu crois pouvoir travailler, tu peux travailler encore plus dur que ça.', 'Kobe Bryant', 'mindset', null, null, null),
  ('q-0200', 'On n''abandonne pas, on ne bat en retraite, on ne fuit pas.', 'Kobe Bryant', 'mindset', null, null, null),
  ('q-0201', 'Tout changement de vie commence par une décision.', 'Tony Robbins', 'mindset', null, null, null),
  ('q-0202', 'L''échec est une partie du succès. Quiconque évite l''échec évite aussi le succès.', 'Tony Robbins', 'mindset', null, null, null),
  ('q-0203', 'Les décisions que nous prenons déterminent notre destin.', 'Tony Robbins', 'mindset', null, null, null),
  ('q-0205', 'La qualité de la vie d''une personne est en rapport direct avec sa volonté d''exceller, quel que soit le domaine où elle s''exerce.', 'Vince Lombardi', 'mindset', null, null, null),
  ('q-0206', 'Si l''important n''est pas de gagner, pourquoi compte-t-on les points ?', 'Vince Lombardi', 'mindset', null, null, null),
  ('q-0207', 'Les conditions essentielles pour réussir sont la patience et la certitude du succès.', 'John D. Rockefeller', 'mindset', null, null, null),
  ('q-0208', 'Si vous voulez réussir, lancez-vous sur de nouveaux chemins plutôt que de parcourir les sentiers usés du succès accepté.', 'John D. Rockefeller', 'mindset', null, null, null),
  ('q-0209', 'La ténacité est une des qualités indispensables pour réussir dans la vie, quel que soit le but à atteindre.', 'John D. Rockefeller', 'mindset', null, null, null),
  ('q-0210', 'Le secret du succès est de faire les choses communes de manière peu commune.', 'John D. Rockefeller', 'mindset', null, null, null),
  ('q-0211', 'Il n''y a qu''un seul patron : le client. Il peut licencier tout le monde, simplement en allant dépenser son argent ailleurs.', 'Sam Walton', 'sales', null, null, null),
  ('q-0213', 'La meilleure raison de lancer une entreprise, c''est de créer du sens.', 'Guy Kawasaki', 'leadership', null, null, null),
  ('q-0214', 'Les vrais entrepreneurs sont motivés par leur passion, non par le profit.', 'Guy Kawasaki', 'mindset', null, null, null),
  ('q-0221', 'Être réaliste est la voie la plus commune vers la médiocrité.', 'Will Smith', 'mindset', null, null, null),
  ('q-0224', 'Un gagnant est un rêveur qui n''abandonne jamais.', 'Nelson Mandela', 'mindset', null, null, null),
  ('q-0225', 'La plus grande gloire n''est pas de ne jamais tomber, mais de se relever à chaque chute.', 'Nelson Mandela', 'mindset', null, null, null),
  ('q-0226', 'Ne me jugez pas par mon succès, jugez-moi par combien de fois je suis tombé et je me suis relevé.', 'Nelson Mandela', 'mindset', null, null, null),
  ('q-0227', 'C''est toujours impossible jusqu''à ce que ça soit fait.', 'Nelson Mandela', 'mindset', null, null, null),
  ('q-0228', 'La confiance en soi est le premier secret du succès.', 'Ralph Waldo Emerson', 'mindset', null, null, null),
  ('q-0229', 'N''allez pas là où le chemin peut mener. Allez là où il n''y a pas de chemin et laissez une trace.', 'Ralph Waldo Emerson', 'mindset', null, null, null),
  ('q-0230', 'Les hommes parlent de la victoire comme d''une chance. C''est le travail qui fait la victoire.', 'Ralph Waldo Emerson', 'mindset', null, null, null),
  ('q-0231', 'Rien de grand ne se fit jamais sans enthousiasme.', 'Ralph Waldo Emerson', 'mindset', null, null, null),
  ('q-0232', 'L''ancêtre de toute action est une pensée.', 'Ralph Waldo Emerson', 'mindset', null, null, null),
  ('q-0233', 'La vie est une aventure audacieuse ou elle n''est rien.', 'Helen Keller', 'mindset', null, null, null),
  ('q-0234', 'Tournez votre visage vers le soleil et vous ne verrez pas les ombres.', 'Helen Keller', 'mindset', null, null, null),
  ('q-0235', 'Aucun pessimiste n''a jamais découvert le secret des étoiles ni ouvert un nouveau chemin pour l''esprit humain.', 'Helen Keller', 'mindset', null, null, null),
  ('q-0236', 'Il y a toujours deux raisons pour faire quelque chose : une bonne raison et la vraie raison !', 'Dale Carnegie', 'mindset', null, null, null),
  ('q-0237', 'Ni les situations ni les gens ne peuvent être améliorés par un facteur externe. Si amélioration il doit y avoir, elle doit venir de l''intérieur.', 'Dale Carnegie', 'mindset', null, null, null),
  ('q-0239', 'Un enfant, un professeur, un livre, un crayon peuvent changer le monde.', 'Malala Yousafzai', 'mindset', null, null, null),
  ('q-0244', 'Les chefs d''entreprise ne peuvent pas être des spectateurs.', 'Howard Schultz', 'leadership', null, null, null),
  ('q-0245', 'Parfois, vous devez créer la chose dont vous voulez faire partie.', 'Howard Schultz', 'mindset', null, null, null),
  ('q-0247', 'Nous devrions construire de grandes choses qui n''existent pas.', 'Larry Page', 'mindset', null, null, null),
  ('q-0248', 'Presque tous ceux qui ont eu une idée quelque peu révolutionnaire ont d''abord été traités de fous.', 'Larry Page', 'mindset', null, null, null),
  ('q-0249', 'L''optimisme est important. Vous devez être un peu ridicule sur les objectifs que vous allez définir.', 'Larry Page', 'mindset', null, null, null),
  ('q-0250', 'Il est très difficile d''échouer complètement, si vous visez assez haut.', 'Larry Page', 'mindset', null, null, null),
  ('q-0251', 'Il vaut mieux agir trop rapidement qu''attendre trop longtemps.', 'Jack Welch', 'mindset', null, null, null),
  ('q-0252', 'Restructurer, c''est un chemin, pas une destination.', 'Jack Welch', 'leadership', null, null, null),
  ('q-0253', 'Contrôlez votre destinée ou quelqu''un d''autre le fera à votre place.', 'Jack Welch', 'mindset', null, null, null),
  ('q-0254', 'Soit vous êtes le meilleur dans ce que vous faites, soit vous ne le faites pas très longtemps.', 'Jack Welch', 'mindset', null, null, null),
  ('q-0256', 'J''attribue mon succès à ceci : je n''ai jamais présenté ou accepté aucune excuse.', 'Earl Nightingale', 'mindset', null, null, null),
  ('q-0257', 'Pour augmenter votre taux de succès, vous devez augmenter votre taux d''échecs.', 'Thomas J. Watson', 'mindset', null, null, null),
  ('q-0258', 'Nos clients les plus mécontents sont notre plus grande source de progrès.', 'Bill Gates', 'sales', null, null, null),
  ('q-0259', 'On ne devient homme qu''en se surpassant.', 'Aristote', 'mindset', null, null, null),
  ('q-0260', 'La stratégie, c''est l''art de faire face à son destin.', 'Peter Drucker', 'leadership', null, null, null),
  ('q-0261', 'Il faut toujours être prêt à négocier, mais ne jamais négocier sans être prêt.', 'Richard Nixon', 'sales', null, null, null),
  ('q-0262', 'On peut tromper tout le monde une partie du temps, et une partie des gens tout le temps, mais on ne peut pas tromper tout le monde tout le temps.', 'Abraham Lincoln', 'mindset', null, null, null),
  ('q-0263', 'Gagner de l''argent est un art, travailler est un art et faire de bonnes affaires est le plus bel art.', 'Andy Warhol', 'finance', null, null, null),
  ('q-0264', 'Le secret des affaires est de savoir quelque chose que personne ne sait.', 'Aristote Onassis', 'finance', null, null, null),
  ('q-0265', 'Vous n''êtes jamais trop vieux pour fixer un nouvel objectif ou rêver un nouveau rêve.', 'C.S. Lewis', 'mindset', null, null, null),
  ('q-0266', 'Seul, nous pouvons faire si peu ; ensemble, nous pouvons faire tant.', 'Helen Keller', 'leadership', null, null, null),
  ('q-0267', 'Le succès n''est pas la clé du bonheur. Le bonheur est la clé du succès.', 'Albert Schweitzer', 'mindset', null, null, null),
  ('q-0268', 'La seule limite à notre réalisation de demain sera nos doutes d''aujourd''hui.', 'Franklin D. Roosevelt', 'mindset', null, null, null),
  ('q-0269', 'Ce n''est pas que je sois si intelligent, c''est juste que je reste avec les problèmes plus longtemps.', 'Albert Einstein', 'mindset', null, null, null),
  ('q-0270', 'Le succès est la somme de petits efforts, répétés jour après jour.', 'Robert Collier', 'mindset', null, null, null),
  ('q-0271', 'La force de l''équipe, c''est chaque membre. La force de chaque membre, c''est l''équipe.', 'Phil Jackson', 'leadership', null, null, null),
  ('q-0272', 'Fixer des objectifs est le premier pas pour transformer l''invisible en visible.', 'Tony Robbins', 'mindset', null, null, null),
  ('q-0273', 'L''avenir appartient à ceux qui croient à la beauté de leurs rêves.', 'Eleanor Roosevelt', 'mindset', null, null, null),
  ('q-0274', 'Croyez que vous pouvez et vous êtes déjà à mi-chemin.', 'Theodore Roosevelt', 'mindset', null, null, null),
  ('q-0275', 'Ce qui est derrière nous et ce qui est devant nous sont de petites choses comparées à ce qui est en nous.', 'Ralph Waldo Emerson', 'mindset', null, null, null),
  ('q-0276', 'Si ce que vous faites ne vous rapproche pas de vos buts, alors c''est que ça vous en éloigne.', 'Brian Tracy', 'mindset', null, null, null),
  ('q-0277', 'En matière commerciale, le succès vient davantage de l''attitude que de l''aptitude.', 'Michael Aguilar', 'sales', null, null, null),
  ('q-0278', 'Les 5 freins à toute vente : pas de besoin, pas de budget, pas d''urgence, pas d''envie, pas de confiance.', 'Zig Ziglar', 'sales', null, null, null),
  ('q-0279', 'Si les gens vous apprécient, ils vous écouteront, mais s''ils ont confiance en vous, ils feront affaire avec vous.', 'Zig Ziglar', 'sales', null, null, null),
  ('q-0280', 'La vente est essentiellement un transfert de sentiments.', 'Zig Ziglar', 'sales', null, null, null),
  ('q-0281', 'Nous considérons nos clients comme des invités, à une fête où nous sommes les hôtes.', 'Jeff Bezos', 'sales', null, null, null),
  ('q-0282', 'Mettre le client en premier. Inventer. Et être patient.', 'Jeff Bezos', 'sales', null, null, null),
  ('q-0283', 'Ne trouvez pas des clients pour vos produits, trouvez des produits pour vos clients.', 'Seth Godin', 'sales', null, null, null),
  ('q-0284', 'Nous plaçons le client en numéro un, l''employé en numéro deux, l''actionnaire en numéro trois.', 'Jack Ma', 'sales', null, null, null),
  ('q-0285', 'On se souvient de la qualité bien plus longtemps que du prix.', 'Guccio Gucci', 'sales', null, null, null),
  ('q-0287', 'Il ne sert à rien d''être le meilleur si on est le seul à le savoir.', 'Richard Branson', 'sales', null, null, null),
  ('q-0289', 'L''entreprise est élue tous les jours par ses clients.', 'François Michelin', 'sales', null, null, null),
  ('q-0290', 'La philosophie commerciale nous enseigne que celui qui ne demande rien n''a rien, et il est déçu.', 'Jean-Jacques Servan-Schreiber', 'sales', null, null, null),
  ('q-0292', 'Quand on ne sait pas où on va, tous les chemins mènent un peu nulle part.', 'Henry Kissinger', 'leadership', null, null, null),
  ('q-0293', 'Si vous voulez vous élever, élevez quelqu''un d''autre.', 'Booker T. Washington', 'leadership', null, null, null),
  ('q-0294', 'L''attitude détermine les actions. Les actions déterminent les résultats.', 'Jim Rohn', 'leadership', null, null, null),
  ('q-0295', 'Un leader est quelqu''un qui connaît le chemin, qui suit le chemin, et qui montre le chemin.', 'John C. Maxwell', 'leadership', null, null, null),
  ('q-0296', 'Si vous ne pouvez pas contrôler vos émotions, vous ne pouvez pas contrôler votre argent.', 'Warren Buffett', 'finance', null, null, null),
  ('q-0297', 'Règle numéro un : ne perdez jamais d''argent. Règle numéro deux : n''oubliez jamais la règle numéro un.', 'Warren Buffett', 'finance', null, null, null),
  ('q-0299', 'En bourse, tu as deux choix : t''enrichir lentement ou t''appauvrir rapidement.', 'Benjamin Graham', 'finance', null, null, null),
  ('q-0300', 'La chance ne sourit qu''aux esprits bien préparés.', 'Louis Pasteur', 'mindset', null, null, null),
  ('q-0301', 'L''enthousiasme est une maladie contagieuse.', 'Voltaire', 'mindset', null, null, null),
  ('q-0302', 'Accepter l''idée de la défaite, c''est être déjà vaincu.', 'Général Foch', 'mindset', null, null, null),
  ('q-0303', 'Ne pensez pas à l''échec, pensez aux opportunités que vous risquez de manquer.', 'Jack Canfield', 'mindset', null, null, null),
  ('q-0304', 'Vous risquez d''être déçu si vous échouez, mais vous êtes condamné si vous n''essayez pas.', 'Beverly Sills', 'mindset', null, null, null),
  ('q-0305', 'Être conscient de son ignorance est le premier pas vers la connaissance.', 'Benjamin Disraeli', 'mindset', null, null, null),
  ('q-0308', 'La façon la plus courante d''abandonner son pouvoir, c''est de penser qu''on n''en a pas.', 'Alice Walker', 'mindset', null, null, null),
  ('q-0312', 'Le leadership n''a rien à voir avec les titres. C''est la capacité à influencer d''autres vies.', 'John C. Maxwell', 'leadership', null, null, null),
  ('q-0314', 'À une époque, le leadership résidait dans les muscles. Aujourd''hui, il réside dans la façon de traiter les gens.', 'Mahatma Gandhi', 'leadership', null, null, null),
  ('q-0316', 'Le leader est celui qui sait inspirer sans éteindre, diriger sans écraser.', 'Maya Angelou', 'leadership', null, null, null),
  ('q-0317', 'Les gens n''achètent pas ce que vous faites, ils achètent pourquoi vous le faites.', 'Simon Sinek', 'leadership', null, 'Commencer par pourquoi', 2009),
  ('q-0318', 'La fonction du leadership est de produire d''autres leaders, pas plus de suiveurs.', 'Ralph Nader', 'leadership', null, null, null),
  ('q-0319', 'Tout le monde porte un panneau invisible autour du cou qui dit : faites-moi sentir que je suis important.', 'Mary Kay Ash', 'leadership', null, null, null),
  ('q-0320', 'Avant d''être un leader, le succès consiste à se développer soi-même. Une fois leader, le succès consiste à faire grandir les autres.', 'Jack Welch', 'leadership', null, null, null),
  ('q-0321', 'Les leaders ne naissent pas, ils sont faits. Et ils sont faits par l''effort acharné.', 'Vince Lombardi', 'leadership', null, null, null),
  ('q-0322', 'Soyez craintifs quand les autres sont avides. Soyez avide quand les autres sont craintifs.', 'Warren Buffett', 'finance', 'Écrite après le krach d''octobre 1987, en review de l''exercice 1986 : Buffett y résume sa discipline face aux mouvements de foule du marché.', 'Lettre aux actionnaires de Berkshire Hathaway', 1986),
  ('q-0323', 'Si vous n''êtes pas prêt à détenir une action pendant 10 ans, ne pensez même pas à la détenir pendant 10 minutes.', 'Warren Buffett', 'finance', 'Dans le même texte que le principe de détention « pour toujours » : un investissement se juge sur l''entreprise, jamais sur l''horizon qu''on lui impose.', 'Lettre aux actionnaires de Berkshire Hathaway', 1996),
  ('q-0324', 'Il ne s''agit pas de prédire la pluie, il s''agit de construire l''arche.', 'Warren Buffett', 'finance', 'La « règle de Noé » : Buffett l''a formulée après avoir lui-même sous-estimé un risque, pour dire qu''anticiper ne vaut rien sans s''y préparer réellement.', 'Lettre aux actionnaires de Berkshire Hathaway', 1981),
  ('q-0325', 'Les quatre mots les plus dangereux dans le monde de l''investissement sont : « cette fois, c''est différent ».', 'John Templeton', 'finance', null, null, null),
  ('q-0326', 'La patience est la clé de l''investissement réussi.', 'John Templeton', 'finance', null, null, null),
  ('q-0327', 'Ne cherchez pas l''aiguille dans la meule de foin : achetez la meule.', 'John C. Bogle', 'finance', null, null, null),
  ('q-0328', 'Investissez dans ce que vous connaissez.', 'Peter Lynch', 'finance', null, null, null),
  ('q-0329', 'Investir n''est pas battre les autres à leur jeu. Il s''agit de se contrôler soi-même.', 'Benjamin Graham', 'finance', null, null, null),
  ('q-0330', 'Les riches investissent leur argent et dépensent ce qui reste.', 'Robert Kiyosaki', 'finance', null, null, null),
  ('q-0331', 'Les pauvres et la classe moyenne travaillent pour de l''argent. Les riches font travailler l''argent.', 'Robert Kiyosaki', 'finance', null, null, null),
  ('q-0332', 'L''éducation obligatoire amène un salaire, l''éducation personnelle amène la fortune.', 'Robert Kiyosaki', 'finance', null, null, null),
  ('q-0333', 'L''important n''est pas d''avoir raison ou tort, mais de savoir combien d''argent on gagne quand on a raison.', 'George Soros', 'finance', null, null, null),
  ('q-0334', 'Le moment d''acheter, c''est quand le sang coule dans les rues.', 'Nathan Rothschild', 'finance', null, null, null),
  ('q-0335', 'On apprend beaucoup plus de ses pertes que de ses gains.', 'Paul Tudor Jones', 'finance', null, null, null),
  ('q-0336', 'N''essayez pas d''acheter aux points bas et de vendre aux points hauts. Seuls les menteurs peuvent faire ça.', 'Bernard Baruch', 'finance', null, null, null),
  ('q-0337', 'La vente commence quand le client dit : non.', 'Elmer G. Leterman', 'sales', null, null, null),
  ('q-0338', 'La raison d''être d''une entreprise est de créer et de garder un client.', 'Theodore Levitt', 'sales', null, null, null),
  ('q-0339', 'Prenez soin du client et l''entreprise prendra soin d''elle-même.', 'Ray Kroc', 'sales', null, null, null),
  ('q-0340', 'Le service client ne doit pas être uniquement un service, il doit concerner l''ensemble de l''entreprise.', 'Tony Hsieh', 'sales', null, null, null),
  ('q-0341', 'Un client qui n''a qu''un seul fournisseur cesse d''être intelligent.', 'François Michelin', 'sales', null, null, null),
  ('q-0342', 'Ce qui compte, c''est le chiffre un : une tasse, un client, un partenaire.', 'Howard Schultz', 'sales', null, null, null),
  ('q-0344', 'Un objectif correctement défini est à moitié atteint.', 'Zig Ziglar', 'sales', null, null, null),
  ('q-0345', 'Pour une vente manquée par excès d''enthousiasme, on en compte cent manquées par faute d''enthousiasme.', 'Zig Ziglar', 'sales', null, null, null),
  ('q-0346', 'Le marketing ne consiste pas à vendre ce que vous produisez, mais à connaître ce dont le consommateur a besoin.', 'Philip Kotler', 'sales', null, null, null),
  ('q-0347', 'L''objectif de la vente est de satisfaire un besoin client, celui du marketing est de comprendre ce besoin.', 'Philip Kotler', 'sales', null, null, null),
  ('q-0348', 'Le marketing s''apprend en un jour ; il faut toute une vie pour le maîtriser.', 'Philip Kotler', 'sales', null, null, null),
  ('q-0349', 'Il est impossible d''être chef d''entreprise sans un minimum d''audace.', 'Carlos Ghosn', 'leadership', null, null, null),
  ('q-0351', 'Si vous vous limitez aux avis des experts, il y a peu de chances que vous innoviez.', 'Carlos Ghosn', 'leadership', null, null, null),
  ('q-0352', 'Une équipe n''est pas un groupe de personnes qui travaillent ensemble. C''est un groupe de personnes qui se font confiance.', 'Simon Sinek', 'leadership', null, null, null),
  ('q-0353', 'Un chef possède un titre, un leader a les autres avec lui.', 'Simon Sinek', 'leadership', null, null, null),
  ('q-0354', 'Bâtir la confiance ne réclame rien de plus que de dire la vérité.', 'Simon Sinek', 'leadership', null, null, null),
  ('q-0356', 'Les managers travaillent avec les processus, les leaders travaillent avec les gens.', 'John C. Maxwell', 'leadership', null, null, null),
  ('q-0357', 'Pour réaliser une grande vision, vous devez avoir une grande équipe.', 'John C. Maxwell', 'leadership', null, null, null),
  ('q-0358', 'La confiance est le fondement de tout bon leadership.', 'John C. Maxwell', 'leadership', null, null, null),
  ('q-0359', 'Investissez dans une entreprise que n''importe quel imbécile peut diriger, parce qu''un jour un imbécile le fera.', 'Charlie Munger', 'finance', null, null, null),
  ('q-0360', 'Si investir était si simple, tout le monde serait riche.', 'Charlie Munger', 'finance', null, null, null),
  ('q-0361', 'Le gros argent n''est pas dans l''achat ou la vente, mais dans l''attente.', 'Charlie Munger', 'finance', null, null, null),
  ('q-0362', 'Vous n''avez pas besoin d''être brillant, juste un peu plus sage que les autres, en moyenne, pendant longtemps.', 'Charlie Munger', 'finance', null, null, null),
  ('q-0363', 'Les riches acquièrent des actifs. Les pauvres et la classe moyenne acquièrent des passifs en pensant que ce sont des actifs.', 'Robert Kiyosaki', 'finance', null, null, null),
  ('q-0364', 'Ce qui compte, ce n''est pas combien d''argent vous faites, mais combien vous parvenez à en conserver.', 'Robert Kiyosaki', 'finance', null, null, null),
  ('q-0365', 'Vous devez voir l''échec comme le début et le milieu, mais ne jamais le considérer comme une fin.', 'Jessica Herrin', 'mindset', null, null, null),
  ('q-0366', 'Peu importe combien de fois vous avez échoué. Vous devez juste avoir raison une fois.', 'Mark Cuban', 'mindset', null, null, null),
  ('q-0367', 'La croissance et le confort ne coexistent pas.', 'Virginia Rometty', 'mindset', null, null, null),
  ('q-0368', 'Le succès arrive généralement à ceux qui sont trop occupés pour le chercher.', 'Henry David Thoreau', 'mindset', null, null, null),
  ('q-0369', 'Je n''ai jamais rêvé de succès. J''ai travaillé pour cela.', 'Estée Lauder', 'mindset', null, null, null),
  ('q-0371', 'Il y a cette joie qui vient de s''asseoir pour résoudre un problème, et de se lever quand c''est fait et que c''est bon.', 'Drew Houston', 'mindset', null, null, null),
  ('q-0372', 'Ne soyez jamais limité par l''imagination limitée des autres.', 'Mae Jemison', 'mindset', null, null, null),
  ('q-0373', 'J''ai toujours fait quelque chose que je n''étais pas tout à fait prête à faire. Je pense que c''est comme ça qu''on grandit.', 'Marissa Mayer', 'mindset', null, null, null),
  ('q-0374', 'Il n''y a pas de meilleure mesure de vos valeurs que la façon dont vous dépensez votre temps.', 'Scott Belsky', 'mindset', null, null, null),
  ('q-0375', 'Une idée ne peut devenir une réalité qu''une fois qu''elle est décomposée en éléments organisés et actionnables.', 'Scott Belsky', 'leadership', null, null, null),
  ('q-0378', 'Être sans peur, ce n''est pas l''absence de peur, c''est la maîtrise de la peur. C''est se relever une fois de plus qu''on ne tombe.', 'Arianna Huffington', 'mindset', null, null, null),
  ('q-0379', 'La persévérance n''est pas une longue course ; c''est plusieurs courses courtes les unes après les autres.', 'Walter Elliot', 'mindset', null, null, null),
  ('q-0380', 'Le succès n''est pas une question de grandeur. C''est une question de constance.', 'Dwayne Johnson', 'mindset', null, null, null),
  ('q-0382', 'Seuls ceux qui prennent le risque d''aller trop loin peuvent découvrir jusqu''où ils peuvent aller.', 'T.S. Eliot', 'mindset', null, null, null),
  ('q-0383', 'La plus grande erreur que vous puissiez faire dans la vie, c''est d''avoir peur de faire des erreurs.', 'John Wooden', 'mindset', null, null, null),
  ('q-0384', 'L''échec est la clé du succès ; chaque erreur nous enseigne quelque chose.', 'Morihei Ueshiba', 'mindset', null, null, null),
  ('q-0385', 'Ne jugez pas chaque jour à la récolte que vous faites, mais aux graines que vous plantez.', 'Robert Louis Stevenson', 'mindset', null, null, null),
  ('q-0386', 'La question n''est pas « qui va me donner l''autorisation de faire ça ? » mais plutôt « qui pourra m''arrêter ? »', 'Ayn Rand', 'mindset', null, null, null),
  ('q-0389', 'La réussite ne se mesure pas à l''argent que vous gagnez mais à votre capacité à changer la vie des gens.', 'Michelle Obama', 'mindset', null, null, null),
  ('q-0390', 'Créez votre propre définition du succès, agissez selon vos propres règles, et construisez la vie dont vous êtes fière.', 'Anne Sweeney', 'mindset', null, null, null),
  ('q-0392', 'La meilleure façon de prédire l''avenir est de l''inventer.', 'Alan Kay', 'mindset', null, null, null),
  ('q-0393', 'Ne te demande pas ce dont le monde a besoin. Ce dont il a besoin, ce sont des gens qui ont trouvé ce qui les fait vivre pleinement.', 'Howard Thurman', 'mindset', null, null, null),
  ('q-0394', 'Si vous ne construisez pas votre rêve, quelqu''un d''autre vous embauchera pour construire les siens.', 'Tony Gaskins', 'mindset', null, null, null),
  ('q-0395', 'Il n''est jamais trop tard pour être ce que vous auriez pu être.', 'George Eliot', 'mindset', null, null, null),
  ('q-0398', 'Si l''on doit se souvenir de tous ses échecs, on ne s''en sort pas.', 'Xavier Niel', 'mindset', null, null, null),
  ('q-0399', 'Il faut avoir le courage de prendre des risques et de ne pas avoir peur de l''échec.', 'Marc Simoncini', 'mindset', null, null, null),
  ('q-0400', 'Point n''est besoin d''espérer pour entreprendre, ni de réussir pour persévérer.', 'Guillaume Ier d''Orange-Nassau', 'mindset', null, null, null),
  ('q-0401', 'Si les opportunités ne frappent pas à la porte, construisez une nouvelle porte.', 'Milton Berle', 'mindset', null, null, null),
  ('q-0402', 'Si tout semble sous contrôle, c''est que vous n''allez pas assez vite.', 'Mario Andretti', 'mindset', null, null, null),
  ('q-0403', 'Il n''y a pas meilleur catalyseur du succès que la curiosité.', 'Michael Dell', 'mindset', null, null, null),
  ('q-0404', 'Il est possible dans certains cas d''être occupé, très occupé, et parfaitement inefficace.', 'Stephen R. Covey', 'mindset', null, null, null),
  ('q-0405', 'La mort de l''entrepreneur porte un nom : isolement.', 'Ernesto Sirolli', 'mindset', null, null, null),
  ('q-0406', 'Certains rêvent d''incroyables réalisations, pendant que d''autres restent éveillés et les font.', 'Nolan Bushnell', 'mindset', null, null, null),
  ('q-0407', 'L''inspiration est périssable. Agissez immédiatement.', 'Naval Ravikant', 'mindset', null, null, null),
  ('q-0408', 'L''échec n''est rien d''autre que la façon dont la vie vous indique que vous n''êtes pas sur la bonne voie.', 'Sara Blakely', 'mindset', null, null, null),
  ('q-0409', 'Ne soyez pas intimidé par ce que vous ne savez pas. Cela peut être votre plus grande force.', 'Sara Blakely', 'mindset', null, null, null),
  ('q-0410', 'L''entrepreneur est cette personne qui saute d''une falaise, et construit un avion au cours de sa chute.', 'Reid Hoffman', 'mindset', null, null, null),
  ('q-0411', 'La volonté, c''est le clou auquel on accroche son projet pour l''avoir toujours devant les yeux.', 'Victor Hugo', 'mindset', null, null, null),
  ('q-0412', 'L''histoire, c''est la rencontre d''une volonté et d''un événement.', 'Charles de Gaulle', 'mindset', null, null, null),
  ('q-0413', 'Délibérer est le fait de plusieurs. Agir est le fait d''un seul.', 'Charles de Gaulle', 'leadership', null, null, null),
  ('q-0414', 'Si tu veux construire un bateau, ne rassemble pas des hommes pour aller chercher du bois, mais donne-leur envie de la mer immense.', 'Antoine de Saint-Exupéry', 'mindset', null, null, null),
  ('q-0415', 'Il faut d''abord savoir ce que l''on veut, il faut ensuite avoir le courage de le dire, il faut ensuite l''énergie de le faire.', 'Georges Clemenceau', 'mindset', null, null, null),
  ('q-0416', 'Évoluer est la plus grande réussite d''une vie, et sa plus belle récompense.', 'Ray Dalio', 'mindset', null, null, null),
  ('q-0417', 'L''échec signifie un dépouillement de l''inessentiel.', 'J.K. Rowling', 'mindset', null, null, null),
  ('q-0419', 'Le succès recèle le germe de sa propre destruction.', 'Andrew Grove', 'mindset', null, null, null),
  ('q-0420', 'Seuls ceux qui dorment ne font pas d''erreurs.', 'Ingvar Kamprad', 'mindset', null, null, null),
  ('q-0425', 'Le succès est fait de 99 % d''échecs.', 'Soichiro Honda', 'mindset', null, null, null),
  ('q-0426', 'Nous avons plus de force que de volonté.', 'La Rochefoucauld', 'mindset', null, null, null),
  ('q-0427', 'Les occasions se présentent habituellement sous la forme d''un dur labeur ; c''est pourquoi la plupart des gens ne les reconnaissent pas.', 'Ann Landers', 'mindset', null, null, null),
  ('q-0429', 'Il ne dépend pas de toi d''être riche, mais il dépend de toi d''être heureux.', 'Épictète', 'mindset', null, null, null),
  ('q-0431', 'Les rêves ne sont pas ce que vous voyez dans votre sommeil, les rêves sont des choses qui ne vous permettent pas de dormir.', 'A.P.J. Abdul Kalam', 'mindset', null, null, null),
  ('q-0434', 'Le présent n''est pas un passé en puissance, il est le moment du choix et de l''action.', 'Simone de Beauvoir', 'mindset', null, null, null),
  ('q-0436', 'La vraie grandeur consiste à être maître de soi-même.', 'Daniel Defoe', 'mindset', null, null, null),
  ('q-0437', 'Toute facilité apparente, toute réussite, sont les fruits d''une rigueur intime.', 'Gérard Bauer', 'mindset', null, null, null),
  ('q-0439', 'Si on veut vivre, il faut prendre des risques.', 'Boris Cyrulnik', 'mindset', null, null, null),
  ('q-0440', 'Je patine là où le palet va aller, pas là où il était.', 'Wayne Gretzky', 'mindset', null, null, null),
  ('q-0442', 'Le parcours était semé d''embûches, mais c''était mal me connaître que d''imaginer que j''abandonnerais la partie dès les premiers obstacles.', 'Simone Veil', 'mindset', null, null, null),
  ('q-0443', 'Le progrès est impossible sans changement et ceux qui ne peuvent changer leur esprit ne peuvent absolument rien changer.', 'George Bernard Shaw', 'mindset', null, null, null),
  ('q-0444', 'Trop souvent, les gens travaillent dur sur la mauvaise chose. Travailler sur la bonne chose est probablement plus important que de travailler dur.', 'Caterina Fake', 'mindset', null, null, null),
  ('q-0451', 'Les entrepreneurs ne demandent pas la permission. Ils agissent pour leur mission.', 'Ryan Lilly', 'mindset', null, null, null),
  ('q-0455', 'Celui qui n''a jamais commis d''erreur n''a jamais tenté quelque chose de nouveau.', 'Albert Einstein', 'mindset', null, null, null),
  ('q-0456', 'L''espérance est un risque à courir.', 'Georges Bernanos', 'mindset', null, null, null),
  ('q-0457', 'Le talent, c''est d''avoir envie de faire quelque chose.', 'Jacques Brel', 'mindset', null, null, null),
  ('q-0460', 'Agir librement, c''est prendre possession de soi.', 'Henri Bergson', 'mindset', null, null, null),
  ('q-0461', 'Oser, c''est d''abord oser l''échec.', 'Charles Pépin', 'mindset', null, null, null),
  ('q-0462', 'La seule chose promise d''avance à l''échec, c''est celle que l''on ne tente pas.', 'Paul-Émile Victor', 'mindset', null, null, null),
  ('q-0464', 'Oser, c''est perdre pied momentanément. Ne pas oser, c''est se perdre soi-même.', 'Søren Kierkegaard', 'mindset', null, null, null),
  ('q-0465', 'On ne réussit ordinairement dans les grandes entreprises qu''en courant de grands dangers.', 'Hérodote', 'mindset', null, null, null),
  ('q-0466', 'Il faut un peu risquer dans la vie, quand on veut avoir quelque chose.', 'Marcel Pagnol', 'mindset', null, null, null),
  ('q-0467', 'On hasarde de perdre en voulant trop gagner.', 'Jean de La Fontaine', 'mindset', null, null, null),
  ('q-0468', 'Le leadership consiste à rendre les autres meilleurs en sa présence et à faire en sorte que cet impact dure en son absence.', 'Sheryl Sandberg', 'leadership', null, null, null),
  ('q-0470', 'Le leadership, c''est l''art de motiver quelqu''un à faire ce que vous voulez qu''il fasse parce qu''il veut le faire.', 'Dwight Eisenhower', 'leadership', null, null, null),
  ('q-0471', 'Le leadership n''est pas une position, mais une action.', 'Donald McGannon', 'leadership', null, null, null),
  ('q-0473', 'Il est difficile d''atteindre des objectifs que vous n''avez jamais fixés.', 'Susan Wojcicki', 'leadership', null, null, null),
  ('q-0474', 'Le secret de la réussite est de savoir s''entourer de gens meilleurs que soi.', 'François Pinault', 'leadership', null, null, null),
  ('q-0478', 'Le bien est l''ennemi du mieux.', 'Jim Collins', 'leadership', null, 'De la performance à l''excellence', 2001),
  ('q-0482', 'L''innovation n''est pas une fin en soi. Encore faut-il la développer pour l''imposer aux clients.', 'Akio Morita', 'leadership', null, null, null),
  ('q-0483', 'Diriger, c''est se dévouer à une idée, à un rêve, à une vision de ce qui peut advenir.', 'John F. Kennedy', 'leadership', null, null, null),
  ('q-0485', 'La confiance rapporte plus que le contrôle.', 'Jean-François Zobrist', 'leadership', null, null, null),
  ('q-0487', 'Gagner de l''argent n''est pas une chose que l''on fait, c''est une compétence que l''on apprend.', 'Naval Ravikant', 'finance', null, null, null),
  ('q-0488', 'La confiance ! C''est ça qui est important, plus que les capitaux propres ou les liquidités.', 'Phil Knight', 'finance', null, null, null),
  ('q-0489', 'Gagner de l''argent n''oblige personne à salir son honneur ou sa conscience.', 'Guy de Rothschild', 'finance', null, null, null),
  ('q-0490', 'Après tout, l''argent disparaît, des amis meurent et vous mourez vous-même, mais votre réputation demeure.', 'Thor Bjorgolfsson', 'finance', null, null, null),
  ('q-0491', 'Faire de l''argent un moyen et non une fin.', 'Pierre Rabhi', 'finance', null, null, null),
  ('q-0493', 'Les riches se concentrent sur les solutions, les pauvres se concentrent sur les problèmes.', 'T. Harv Eker', 'finance', null, null, null),
  ('q-0494', 'L''argent, c''est la liberté monnayée.', 'Fiodor Dostoïevski', 'finance', null, null, null),
  ('q-0495', 'N''estime l''argent ni plus ni moins qu''il ne vaut : c''est un bon serviteur et un mauvais maître.', 'Alexandre Dumas', 'finance', null, null, null),
  ('q-0496', 'L''argent qu''on possède est celui de la liberté ; celui qu''on pourchasse est celui de la servitude.', 'Jean-Jacques Rousseau', 'finance', null, null, null),
  ('q-0497', 'Quand j''étais jeune, je croyais que, dans la vie, l''argent était le plus important. Maintenant que je suis vieux, je le sais !', 'Oscar Wilde', 'finance', null, null, null),
  ('q-0498', 'Il y a tellement de choses plus importantes dans la vie que l''argent, mais il faut tellement d''argent pour les acquérir.', 'Groucho Marx', 'finance', null, null, null),
  ('q-0499', 'Ce n''est pas parce que vous pouvez vous le permettre que vous devez l''acheter.', 'Suze Orman', 'finance', null, null, null),
  ('q-0500', 'Ma philosophie d''investissement, généralement, avec des exceptions, est d''acheter quelque chose quand personne n''en veut.', 'Carl Icahn', 'finance', null, null, null),
  ('q-0503', 'Privilégiez le client, non la vente.', 'Katherine Barchetti', 'sales', null, null, null),
  ('q-0504', 'Ne célébrez pas la clôture d''une vente, célébrez l''ouverture d''une relation.', 'Patricia Fripp', 'sales', null, null, null),
  ('q-0507', 'Si vous ne prenez pas soin de votre client, votre concurrent le fera.', 'Bob Hooey', 'sales', null, null, null),
  ('q-0508', 'Intéressez-vous à créer de la valeur pour vos clients. Si vous comprenez bien cette partie, la vente est facile.', 'Anthony Iannarino', 'sales', null, null, null),
  ('q-0509', 'Les grands vendeurs sont des créateurs de relations qui apportent de la valeur et aident leurs clients à gagner.', 'Jeffrey Gitomer', 'sales', null, null, null),
  ('q-0510', 'L''éthique et les valeurs d''un vendeur contribuent davantage au succès des ventes que les techniques ou les stratégies.', 'Ron Willingham', 'sales', null, null, null),
  ('q-0511', 'Les meilleures questions de vente témoignent de votre expertise.', 'Jill Konrath', 'sales', null, null, null),
  ('q-0512', 'Ne vous plaignez jamais d''un client difficile, car il est la cause de vos progrès.', 'Auguste Detoeuf', 'sales', null, null, null),
  ('q-0513', 'Parler est un besoin, écouter est un art.', 'Goethe', 'sales', null, null, null),
  ('q-0514', 'Les clients ne se soucient pas du tout de savoir si vous concluez la transaction ou non. Ils se soucient d''améliorer leur entreprise.', 'Aaron Ross', 'sales', null, null, null),
  ('q-0516', 'Être premier sur un marché n''est pas tout. La fidélité des clients est tout.', 'Stefan Persson', 'sales', null, null, null),
  ('q-0518', 'Dire la vérité est la meilleure campagne marketing.', 'Richie Norton', 'sales', null, null, null),
  ('q-0519', 'Le bon entrepreneur, c''est vous : il n''y a pas de profil type pour réussir.', 'Xavier Niel', 'mindset', null, null, null),
  ('q-0520', 'On peut casser les codes d''un secteur et oser ce que personne n''a osé faire.', 'Xavier Niel', 'leadership', null, null, null),
  ('q-0522', 'L''échec n''est pas le contraire du succès, c''est une étape nécessaire pour y parvenir.', 'Marc Simoncini', 'mindset', null, null, null),
  ('q-0524', 'Le cœur a ses raisons que la raison ne connaît point.', 'Blaise Pascal', 'mindset', null, 'Pensées', 1670),
  ('q-0525', 'L''essentiel est invisible pour les yeux.', 'Antoine de Saint-Exupéry', 'mindset', 'Ce que le renard confie au Petit Prince avant de le laisser repartir, après lui avoir appris ce qu''apprivoiser veut dire.', 'Le Petit Prince', 1943),
  ('q-0526', 'Fais de ta vie un rêve, et d''un rêve, une réalité.', 'Antoine de Saint-Exupéry', 'mindset', null, null, null),
  ('q-0527', 'L''ambition s''accorde mal avec la paresse.', 'La Rochefoucauld', 'mindset', null, null, null),
  ('q-0529', 'Ne pas avoir peur d''échouer compte plus que ce qu''on apprend à l''école.', 'Sara Blakely', 'mindset', null, null, null),
  ('q-0531', 'Terminé vaut mieux que parfait : mieux vaut avancer qu''attendre la perfection.', 'Sheryl Sandberg', 'mindset', null, null, null),
  ('q-0532', 'Demandez-vous : que ferais-je si je n''avais pas peur ? Puis faites-le.', 'Sheryl Sandberg', 'mindset', null, null, null),
  ('q-0534', 'Si vous n''avez pas honte de la première version de votre produit, vous avez lancé trop tard.', 'Reid Hoffman', 'leadership', null, null, null),
  ('q-0535', 'L''échec n''est pas l''opposé de la réussite, il en fait partie.', 'Arianna Huffington', 'mindset', null, null, null),
  ('q-0536', 'Le succès peut pousser à désapprendre les habitudes qui nous ont fait réussir.', 'Satya Nadella', 'mindset', null, null, null),
  ('q-0537', 'Il faut passer d''une culture du tout savoir à une culture du tout apprendre.', 'Satya Nadella', 'leadership', null, null, null),
  ('q-0539', 'On peut se focaliser sur les obstacles, ou se concentrer pour franchir le mur.', 'Tim Cook', 'mindset', null, null, null),
  ('q-0540', 'Le poison le plus dangereux, c''est le sentiment d''avoir réussi.', 'Ingvar Kamprad', 'mindset', null, null, null),
  ('q-0541', 'Le temps est votre ressource la plus précieuse : une fois perdu, il est perdu pour de bon.', 'Ingvar Kamprad', 'mindset', null, null, null),
  ('q-0544', 'Personne ne voit l''entrepreneuriat comme une survie, pourtant c''est exactement ça.', 'Anita Roddick', 'leadership', null, null, null),
  ('q-0545', 'Il est impossible de vivre sans jamais échouer, à moins de vivre trop prudemment pour vivre vraiment.', 'J.K. Rowling', 'mindset', null, null, null),
  ('q-0546', 'Notre seul vrai plan stratégique, c''est d''agir, tout simplement.', 'Herb Kelleher', 'leadership', null, null, null),
  ('q-0547', 'Le succès est lié à l''action : ceux qui réussissent avancent sans cesse, malgré les erreurs.', 'Conrad Hilton', 'mindset', null, null, null),
  ('q-0548', 'Faites des erreurs, mais faites-les plus vite que les autres.', 'Andrew Grove', 'mindset', null, null, null),
  ('q-0549', 'Jouez des jeux à long terme, avec des gens qui jouent aussi le long terme.', 'Naval Ravikant', 'mindset', null, null, null),
  ('q-0550', 'Recherchez la richesse, pas l''argent ni le statut.', 'Naval Ravikant', 'finance', null, null, null),
  ('q-0551', 'Le revenu est la meilleure forme de financement.', 'Naval Ravikant', 'finance', null, null, null),
  ('q-0552', 'Dans une startup, l''exécution est tout.', 'Paul Graham', 'leadership', null, null, null),
  ('q-0553', 'N''embauchez pas de génies toxiques : le coût pour l''esprit d''équipe est trop élevé.', 'Reed Hastings', 'leadership', null, null, null),
  ('q-0555', 'Mon but n''est pas d''échouer vite, mais de réussir sur la durée : ce n''est pas la même chose.', 'Marc Andreessen', 'leadership', null, null, null),
  ('q-0556', 'Les mauvais managers embauchent de très mauvais employés car ils se sentent menacés par les meilleurs.', 'Marc Andreessen', 'leadership', null, null, null),
  ('q-0557', 'Chaque décision difficile mais juste vous rend un peu plus courageux.', 'Ben Horowitz', 'mindset', null, null, null),
  ('q-0558', 'Un fondateur doit croire qu''une solution existe et la chercher, sans se soucier des probabilités.', 'Ben Horowitz', 'leadership', null, null, null),
  ('q-0559', 'Toute grande entreprise repose sur un secret caché du reste du monde.', 'Peter Thiel', 'mindset', null, null, null),
  ('q-0560', 'La concurrence tue les profits ; visez plutôt un monopole créatif qui profite à tous.', 'Peter Thiel', 'finance', null, null, null),
  ('q-0561', 'On voulait des voitures volantes, on a eu 140 caractères.', 'Peter Thiel', 'mindset', 'Formule d''ouverture du manifeste de son fonds d''investissement, pour dénoncer une innovation qui se serait repliée sur le numérique en délaissant le monde physique.', 'Manifeste de Founders Fund', 2011),
  ('q-0562', 'Si ça ne vend pas, ce n''est pas créatif.', 'David Ogilvy', 'sales', null, null, null),
  ('q-0563', 'Dites la vérité, mais rendez-la fascinante : on n''achète pas ce qui nous ennuie.', 'David Ogilvy', 'sales', null, null, null),
  ('q-0564', 'Si chacun de nous embauche des gens plus petits que lui, nous deviendrons une entreprise de nains.', 'David Ogilvy', 'leadership', null, null, null),
  ('q-0565', 'Les grands battants sont portés non par la quête du succès, mais par la peur de l''échec.', 'Larry Ellison', 'mindset', null, null, null),
  ('q-0566', 'Quand on innove, il faut être prêt à ce que tout le monde vous dise que vous êtes fou.', 'Larry Ellison', 'mindset', null, null, null),
  ('q-0567', 'Pas besoin d''être un génie ou un visionnaire pour réussir : il faut un cadre et un rêve.', 'Michael Dell', 'mindset', null, null, null),
  ('q-0568', 'Les entreprises réussissent ou échouent selon leur capacité à transformer la donnée en décisions.', 'Michael Dell', 'leadership', null, null, null),
  ('q-0569', 'Le but du marketing est de rendre la vente superflue.', 'Peter Drucker', 'sales', null, 'Les Fondements du marketing', null),
  ('q-0570', 'Les gens détestent qu''on leur vende, mais ils adorent acheter.', 'Jeffrey Gitomer', 'sales', null, null, null),
  ('q-0571', 'Le marketing ne consiste plus à parler des produits que vous fabriquez, mais à raconter des histoires.', 'Seth Godin', 'sales', null, null, null),
  ('q-0572', 'Approchez chaque client avec l''idée de l''aider à résoudre un problème, pas de lui vendre un produit.', 'Brian Tracy', 'sales', null, null, null),
  ('q-0573', 'Faites de votre client le héros de votre histoire.', 'Ann Handley', 'sales', null, null, null),
  ('q-0574', 'La meilleure publicité est celle que font les clients satisfaits.', 'Philip Kotler', 'sales', null, null, null),
  ('q-0575', 'Si vous essayez de plaire à tout le monde, vous n''intéresserez personne.', 'Seth Godin', 'sales', null, null, null),
  ('q-0576', 'Vendre, ce n''est pas convaincre quelqu''un d''acheter, c''est l''aider à décider.', 'Zig Ziglar', 'sales', null, null, null),
  ('q-0577', 'La qualité d''un service se mesure à la façon dont on répare ses erreurs.', 'Donald Porter', 'sales', null, null, null),
  ('q-0578', 'Rapprochez-vous plus que jamais de vos clients. Si près que vous leur direz ce dont ils ont besoin avant qu''ils s''en rendent compte.', 'Steve Jobs', 'sales', null, null, null),
  ('q-0579', 'Le prix est ce que vous payez, la valeur est ce que vous obtenez.', 'Warren Buffett', 'finance', 'Buffett y attribue explicitement la leçon à son mentor Benjamin Graham, plutôt que de se l''approprier.', 'Lettre aux actionnaires de Berkshire Hathaway', 2008),
  ('q-0580', 'À court terme le marché est une machine à voter ; à long terme, c''est une balance.', 'Benjamin Graham', 'finance', null, 'L''Investisseur intelligent', 1949),
  ('q-0581', 'Montrez-moi les incitations et je vous montrerai le résultat.', 'Charlie Munger', 'finance', null, null, null),
  ('q-0582', 'Devenir riche et le rester sont deux compétences complètement différentes.', 'Morgan Housel', 'finance', null, null, null),
  ('q-0583', 'Ce n''est pas votre salaire qui vous enrichit, c''est vos habitudes de dépense.', 'Charles A. Jaffe', 'finance', null, null, null),
  ('q-0585', 'Un budget, c''est dire à son argent où aller au lieu de se demander où il est passé.', 'Dave Ramsey', 'finance', null, null, null),
  ('q-0586', 'Le management c''est bien faire les choses ; le leadership c''est faire les bonnes choses.', 'Peter Drucker', 'leadership', null, null, null),
  ('q-0587', 'Le leadership, ce n''est pas être aux commandes. C''est prendre soin de ceux dont on a la charge.', 'Simon Sinek', 'leadership', null, null, null),
  ('q-0589', 'Le leadership est l''art d''obtenir plus que ce que la science du management juge possible.', 'Colin Powell', 'leadership', null, null, null),
  ('q-0590', 'Prenez soin des gens, du produit et des profits — dans cet ordre.', 'Ben Horowitz', 'leadership', null, null, null),
  ('q-0591', 'Seuls les paranoïaques survivent.', 'Andrew Grove', 'leadership', 'Titre du livre où Grove, alors patron d''Intel, raconte les « points d''inflexion stratégiques » qui peuvent emporter une entreprise dominante.', 'Livre « Only the Paranoid Survive »', 1996),
  ('q-0592', 'Embauchez des gens plus intelligents que vous, puis laissez-les faire leur travail.', 'Steve Jobs', 'leadership', null, null, null),
  ('q-0593', 'Un dirigeant doit dire la vérité, surtout quand elle est mauvaise.', 'Ben Horowitz', 'leadership', null, null, null),
  ('q-0595', 'Un bon dirigeant assume plus que sa part de responsabilité et prend moins que sa part de mérite.', 'Arnold H. Glasow', 'leadership', null, null, null),
  ('q-0596', 'Le meilleur chef est celui dont on remarque à peine l''existence.', 'Lao Tseu', 'leadership', null, 'Tao Tö King, chapitre 17', null),
  ('q-0597', 'L''obstacle à l''action fait avancer l''action. Ce qui se met en travers du chemin devient le chemin.', 'Marc Aurèle', 'mindset', 'Écrit pour lui-même pendant ses campagnes militaires, dans un carnet jamais destiné à la publication.', 'Pensées pour moi-même, livre V', null),
  ('q-0598', 'Ce ne sont pas les choses qui troublent les hommes, mais l''opinion qu''ils en ont.', 'Épictète', 'mindset', null, 'Manuel d''Épictète, V', null),
  ('q-0599', 'Vous ne vous élevez pas au niveau de vos objectifs, vous retombez au niveau de vos systèmes.', 'James Clear', 'mindset', null, 'Un rien peut tout changer', 2018),
  ('q-0601', 'La douleur plus la réflexion égale le progrès.', 'Ray Dalio', 'mindset', null, null, null),
  ('q-0602', 'La concurrence est pour les perdants.', 'Peter Thiel', 'sales', 'Thiel y soutient que la concurrence pure détruit les marges et que les entreprises durables sont celles qui échappent à la concurrence, pas celles qui la gagnent.', 'Essai « Competition Is for Losers », Wall Street Journal', 2014),
  ('q-0603', 'Il vaut mieux avoir cent personnes qui vous adorent que cent mille qui vous trouvent sympathique.', 'Peter Thiel', 'sales', null, null, null),
  ('q-0604', 'Faites des choses qui ne passent pas à l''échelle.', 'Paul Graham', 'sales', 'Conseil à contre-courant adressé aux fondateurs : au début, il faut recruter ses premiers utilisateurs un par un, à la main, précisément parce que ça ne tient pas à grande échelle.', 'Essai « Do Things That Don''t Scale »', 2013),
  ('q-0605', 'Le logiciel est en train de dévorer le monde.', 'Marc Andreessen', 'sales', 'Essai écrit alors que les logiciels commençaient à remplacer des industries entières ; le titre est devenu la formule de référence pour décrire cette bascule.', 'Essai « Why Software Is Eating the World », Wall Street Journal', 2011),
  ('q-0606', 'Le seul moyen de gagner est d''apprendre plus vite que tout le monde.', 'Eric Ries', 'sales', null, null, null),
  ('q-0608', 'Il faut commencer par l''expérience client et remonter vers la technologie, jamais l''inverse.', 'Steve Jobs', 'sales', null, null, null),
  ('q-0609', 'Il faut accepter d''être incompris pendant longtemps.', 'Jeff Bezos', 'sales', null, null, null),
  ('q-0610', 'Ce qui compte, ce n''est pas ce que vous vendez, c''est le problème que vous résolvez.', 'Clayton Christensen', 'sales', null, null, null),
  ('q-0611', 'Les gens n''achètent pas une perceuse, ils achètent un trou dans leur mur.', 'Theodore Levitt', 'sales', 'Formulation devenue le résumé de tout le marketing moderne : le client n''achète pas un produit, il achète le résultat qu''il en attend.', '« Marketing Myopia », Harvard Business Review', 1960),
  ('q-0614', 'Faites ce que vous faites si bien que les gens auront envie de revenir et d''amener leurs amis.', 'Walt Disney', 'sales', null, null, null),
  ('q-0615', 'On ne construit pas une réputation sur ce qu''on a l''intention de faire.', 'Henry Ford', 'sales', null, null, null),
  ('q-0616', 'Si vous avez le temps de flâner, vous avez le temps de nettoyer.', 'Ray Kroc', 'sales', 'Règle de terrain d''un homme qui inspectait lui-même les restaurants et jugeait la propreté aussi importante que la cuisine.', null, null),
  ('q-0617', 'Le doute tue plus de rêves que l''échec ne le fera jamais.', 'Suzy Kassem', 'sales', null, null, null),
  ('q-0618', 'Créez quelque chose que les gens veulent vraiment. C''est tout.', 'Paul Graham', 'sales', null, null, null),
  ('q-0620', 'Quelqu''un est assis à l''ombre aujourd''hui parce qu''un autre a planté un arbre il y a longtemps.', 'Warren Buffett', 'finance', null, null, null),
  ('q-0621', 'Les chaînes de l''habitude sont trop légères pour être senties, jusqu''à ce qu''elles deviennent trop lourdes pour être brisées.', 'Warren Buffett', 'finance', 'Une formule qui remonte en réalité à l''écrivain anglais Samuel Johnson au XVIIIe siècle ; Buffett la reprend sans se l''attribuer pour parler du poids des habitudes de gestion.', null, null),
  ('q-0623', 'Il faut beaucoup de temps pour devenir riche lentement, et c''est précisément pour cela que peu de gens le font.', 'Charlie Munger', 'finance', null, null, null),
  ('q-0624', 'Tout ce que je veux savoir, c''est où je vais mourir, comme ça je n''irai jamais.', 'Charlie Munger', 'finance', null, null, null),
  ('q-0625', 'L''investisseur avisé est un réaliste qui vend aux optimistes et achète aux pessimistes.', 'Benjamin Graham', 'finance', null, null, null),
  ('q-0626', 'L''ennemi principal de l''investisseur, c''est probablement lui-même.', 'Benjamin Graham', 'finance', null, null, null),
  ('q-0627', 'Le temps est l''ami des belles entreprises et l''ennemi des médiocres.', 'Warren Buffett', 'finance', null, null, null),
  ('q-0628', 'Ne me dites pas ce que vous pensez, montrez-moi votre portefeuille.', 'Nassim Nicholas Taleb', 'finance', null, null, null),
  ('q-0629', 'La richesse, c''est ce que vous ne voyez pas : les voitures non achetées, les sacs non achetés.', 'Morgan Housel', 'finance', null, 'La Psychologie de l''argent', 2020),
  ('q-0630', 'Le plus grand dividende que l''argent puisse verser, c''est la maîtrise de votre temps.', 'Morgan Housel', 'finance', null, 'La Psychologie de l''argent', 2020),
  ('q-0631', 'Ce ne sont pas les revenus qui font la richesse, c''est l''écart entre ce que vous gagnez et ce que vous dépensez.', 'Thomas J. Stanley', 'finance', null, null, null),
  ('q-0632', 'Payez-vous en premier.', 'George S. Clason', 'finance', null, null, null),
  ('q-0633', 'Une partie de tout ce que vous gagnez vous appartient, à vous et à personne d''autre.', 'George S. Clason', 'finance', null, null, null),
  ('q-0635', 'Le temps passé sur le marché bat le fait de vouloir choisir le bon moment.', 'Peter Lynch', 'finance', null, null, null),
  ('q-0636', 'Bien plus d''argent a été perdu par des investisseurs à essayer d''anticiper les corrections qu''à en subir.', 'Peter Lynch', 'finance', null, null, null),
  ('q-0637', 'Il vaut mieux acheter une entreprise formidable à un prix correct qu''une entreprise correcte à un prix formidable.', 'Warren Buffett', 'finance', 'Tirée du bilan que Buffett dresse de ses vingt-cinq premières années à la tête de Berkshire, où il reconnaît avoir trop longtemps cherché la bonne affaire plutôt que la bonne entreprise.', 'Lettre aux actionnaires de Berkshire Hathaway, section « Mistakes of the First Twenty-Five Years »', 1989),
  ('q-0638', 'Ce n''est pas le critique qui compte, ni celui qui montre comment l''homme fort a trébuché. Le mérite revient à celui qui est dans l''arène.', 'Theodore Roosevelt', 'leadership', 'Extrait du passage dit « L''homme dans l''arène », prononcé à la Sorbonne un an après avoir quitté la Maison-Blanche. Roosevelt y défend ceux qui agissent contre ceux qui commentent.', 'Discours « Citizenship in a Republic », Sorbonne, Paris', 1910),
  ('q-0639', 'Faites ce que vous pouvez, avec ce que vous avez, là où vous êtes.', 'Theodore Roosevelt', 'leadership', null, null, null),
  ('q-0640', 'Le meilleur dirigeant est celui qui a assez de bon sens pour choisir des gens capables, et assez de retenue pour ne pas se mêler de leur travail.', 'Theodore Roosevelt', 'leadership', null, null, null),
  ('q-0641', 'La difficulté attire l''homme de caractère, car c''est en l''étreignant qu''il se réalise lui-même.', 'Charles de Gaulle', 'leadership', null, null, null),
  ('q-0642', 'On ne fait rien de grand sans de grands hommes, et ceux-ci le sont pour l''avoir voulu.', 'Charles de Gaulle', 'leadership', null, null, null),
  ('q-0643', 'Le prix de la grandeur, c''est la responsabilité.', 'Winston Churchill', 'leadership', null, null, null),
  ('q-0644', 'Un chef est un marchand d''espérance.', 'Napoléon Bonaparte', 'leadership', null, null, null),
  ('q-0645', 'Ne demandez pas ce que votre pays peut faire pour vous, demandez ce que vous pouvez faire pour votre pays.', 'John F. Kennedy', 'leadership', 'Prononcé par un président de 43 ans, le plus jeune jamais élu, en pleine guerre froide et deux mois avant la création des Peace Corps qu''annonce cet appel.', 'Discours d''investiture, Washington', 1961),
  ('q-0646', 'Le changement est la loi de la vie. Ceux qui ne regardent que le passé ou le présent manqueront à coup sûr l''avenir.', 'John F. Kennedy', 'leadership', null, null, null),
  ('q-0647', 'Les problèmes du monde ne peuvent être résolus par les sceptiques dont l''horizon se limite aux réalités visibles.', 'John F. Kennedy', 'leadership', null, null, null),
  ('q-0648', 'L''effort et le courage ne suffisent pas sans but ni direction.', 'John F. Kennedy', 'leadership', null, null, null),
  ('q-0649', 'Un dirigeant est un homme qui a besoin des autres.', 'Paul Valéry', 'leadership', null, null, null),
  ('q-0650', 'La qualité d''un dirigeant se mesure aux normes qu''il se fixe à lui-même.', 'Ray Kroc', 'leadership', null, null, null),
  ('q-0651', 'Les gens ne quittent pas des entreprises, ils quittent des managers.', 'Marcus Buckingham', 'leadership', null, null, null),
  ('q-0652', 'Mettez d''abord les bonnes personnes dans le bus, ensuite décidez où aller.', 'Jim Collins', 'leadership', null, 'De la performance à l''excellence', 2001),
  ('q-0653', 'Commencez avec la fin en tête.', 'Stephen R. Covey', 'leadership', null, 'Les 7 habitudes de ceux qui réalisent tout ce qu''ils entreprennent', 1989),
  ('q-0654', 'Cherchez d''abord à comprendre, ensuite à être compris.', 'Stephen R. Covey', 'leadership', null, 'Les 7 habitudes de ceux qui réalisent tout ce qu''ils entreprennent', 1989),
  ('q-0656', 'Recrutez lentement, licenciez vite.', 'Ray Dalio', 'leadership', null, null, null),
  ('q-0657', 'Une organisation excellente n''est pas celle où il n''y a pas de problèmes, c''est celle où les problèmes remontent vite.', 'Ray Dalio', 'leadership', null, null, null),
  ('q-0658', 'La transparence radicale n''est pas confortable, mais elle est efficace.', 'Ray Dalio', 'leadership', null, null, null),
  ('q-0659', 'Notre culture, c''est la liberté et la responsabilité.', 'Reed Hastings', 'leadership', null, null, null),
  ('q-0660', 'Le talent dense attire le talent dense.', 'Reed Hastings', 'leadership', null, null, null),
  ('q-0661', 'L''empathie n''est pas un luxe pour un dirigeant, c''est un outil de travail.', 'Satya Nadella', 'leadership', null, null, null),
  ('q-0662', 'Notre secteur ne respecte pas la tradition, il ne respecte que l''innovation.', 'Satya Nadella', 'leadership', null, null, null),
  ('q-0663', 'Le leadership, c''est aussi savoir quand se taire.', 'Indra Nooyi', 'leadership', null, null, null),
  ('q-0664', 'Supposez toujours la bonne intention chez votre interlocuteur.', 'Indra Nooyi', 'leadership', null, null, null),
  ('q-0665', 'Si vous voulez aller vite, allez seul. Si vous voulez aller loin, allez ensemble.', 'Proverbe africain', 'leadership', null, null, null),
  ('q-0667', 'La seule chose que nous devons craindre, c''est la crainte elle-même.', 'Franklin D. Roosevelt', 'leadership', 'Premier discours d''investiture, au creux de la Grande Dépression : un adulte américain sur quatre est sans emploi et les banques ferment les unes après les autres.', 'Premier discours d''investiture', 1933),
  ('q-0668', 'Un bon plan exécuté aujourd''hui vaut mieux qu''un plan parfait exécuté la semaine prochaine.', 'George S. Patton', 'leadership', null, null, null),
  ('q-0669', 'Ne dites pas aux gens comment faire les choses. Dites-leur quoi faire et laissez-les vous surprendre par leur ingéniosité.', 'George S. Patton', 'leadership', 'Principe de commandement d''un général réputé pour son exigence, qui tenait pourtant à laisser l''initiative à ses subordonnés.', null, null),
  ('q-0670', 'Restez affamés, restez fous.', 'Steve Jobs', 'mindset', 'Jobs conclut son discours en citant la formule d''adieu du dernier numéro du Whole Earth Catalog, publication qui l''a marqué dans sa jeunesse — la phrase n''est donc pas de lui à l''origine.', 'Discours de remise des diplômes, Université Stanford (citant le Whole Earth Catalog, 1974)', 2005),
  ('q-0671', 'On ne peut pas relier les points en regardant devant soi, seulement en regardant en arrière.', 'Steve Jobs', 'mindset', 'Jobs y raconte avoir suivi, sans but apparent, un cours de calligraphie après avoir quitté l''université — devenu dix ans plus tard la typographie soignée du Macintosh.', 'Discours de remise des diplômes, Université Stanford', 2005),
  ('q-0672', 'Je n''ai pas échoué. J''ai simplement trouvé dix mille façons qui ne fonctionnent pas.', 'Thomas Edison', 'mindset', 'Réponse d''Edison à un journaliste qui lui demandait ce que ça faisait d''avoir échoué des milliers de fois avant de mettre au point la lampe à incandescence.', null, null),
  ('q-0673', 'La vie se rétrécit ou s''élargit à proportion de notre courage.', 'Anaïs Nin', 'mindset', null, null, null),
  ('q-0674', 'Vous êtes la moyenne des cinq personnes que vous fréquentez le plus.', 'Jim Rohn', 'mindset', null, null, null),
  ('q-0675', 'Ne souhaitez pas que ce soit plus facile, souhaitez d''être meilleur.', 'Jim Rohn', 'mindset', null, null, null),
  ('q-0676', 'Ce que l''esprit peut concevoir et croire, il peut le réaliser.', 'Napoleon Hill', 'mindset', null, null, null),
  ('q-0677', 'Devenir vaut mieux qu''être.', 'Carol Dweck', 'mindset', null, null, null),
  ('q-0678', 'Rien dans la vie n''a autant d''importance que vous ne le pensez pendant que vous y pensez.', 'Daniel Kahneman', 'mindset', null, null, null),
  ('q-0679', 'J''ai raté plus de neuf mille tirs dans ma carrière. C''est pour cela que je réussis.', 'Michael Jordan', 'mindset', 'Texte d''une publicité Nike entièrement consacrée à ses échecs, diffusée alors qu''il était déjà considéré comme le meilleur joueur de l''histoire.', 'Publicité Nike « Failure »', 1997),
  ('q-0680', 'On rate cent pour cent des tirs qu''on ne tente pas.', 'Wayne Gretzky', 'mindset', null, null, null),
  ('q-0681', 'Je détestais chaque minute d''entraînement, mais je me disais : souffre maintenant et vis le reste de ta vie en champion.', 'Muhammad Ali', 'mindset', null, null, null),
  ('q-0682', 'L''homme qui n''a pas d''imagination n''a pas d''ailes.', 'Muhammad Ali', 'mindset', null, null, null),
  ('q-0683', 'Le job n''est pas fini.', 'Kobe Bryant', 'mindset', null, null, null),
  ('q-0684', 'Les gens oublieront ce que vous avez dit et ce que vous avez fait, mais jamais ce que vous leur avez fait ressentir.', 'Maya Angelou', 'mindset', null, null, null),
  ('q-0685', 'Rien ne fonctionnera si vous ne le faites pas.', 'Maya Angelou', 'mindset', null, null, null),
  ('q-0686', 'Aujourd''hui est dur, demain sera pire, mais après-demain sera magnifique. La plupart abandonnent le soir du deuxième jour.', 'Jack Ma', 'mindset', null, null, null),
  ('q-0687', 'Chaque action que vous entreprenez est un vote pour la personne que vous voulez devenir.', 'James Clear', 'mindset', null, 'Un rien peut tout changer', 2018),
  ('q-0688', 'La passion est courante, la persévérance est rare.', 'Angela Duckworth', 'mindset', null, null, null),
  ('q-0689', 'Le talent, c''est le potentiel. L''effort, c''est ce qui le transforme en résultat.', 'Angela Duckworth', 'mindset', null, null, null),
  ('q-0691', 'Tu as pouvoir sur ton esprit, pas sur les évènements extérieurs. Comprends cela et tu trouveras la force.', 'Marc Aurèle', 'mindset', null, null, null),
  ('q-0692', 'Nous souffrons plus souvent en imagination qu''en réalité.', 'Sénèque', 'mindset', null, 'Lettres à Lucilius, lettre 13', null),
  ('q-0693', 'Ce n''est pas ce qui t''arrive qui compte, mais la façon dont tu y réagis.', 'Épictète', 'mindset', null, null, null),
  ('q-0694', 'Ne cherche pas que les évènements arrivent comme tu veux, mais veuille les évènements comme ils arrivent.', 'Épictète', 'mindset', null, 'Manuel d''Épictète, VIII', null),
  ('q-0695', 'Le premier pas n''emmène pas là où vous voulez aller, mais il vous sort de là où vous êtes.', 'James Clear', 'mindset', null, null, null),
  ('q-0696', 'Connaître les autres, c''est sagesse. Se connaître soi-même, c''est sagesse supérieure.', 'Lao Tseu', 'mindset', null, 'Tao Tö King, chapitre 33', null),
  ('q-0697', 'Le succès, c''est de tomber sept fois et de se relever huit.', 'Proverbe japonais', 'mindset', null, null, null),
  ('q-0699', 'Ce qui ne nous tue pas nous rend plus forts.', 'Friedrich Nietzsche', 'mindset', null, 'Le Crépuscule des idoles', 1888),
  ('q-0700', 'Celui qui a un pourquoi qui lui tient lieu de but peut supporter presque n''importe quel comment.', 'Friedrich Nietzsche', 'mindset', null, 'Le Crépuscule des idoles', 1888),
  ('q-0701', 'La plus grande aventure, c''est de vivre la vie de ses rêves.', 'Oprah Winfrey', 'mindset', null, null, null),
  ('q-0702', 'Transformez vos blessures en sagesse.', 'Oprah Winfrey', 'mindset', null, null, null),
  ('q-0703', 'Échouer, ce n''est pas ne pas réussir, c''est ne pas essayer.', 'Sara Blakely', 'mindset', null, null, null),
  ('q-0705', 'La perfection est atteinte non pas lorsqu''il n''y a plus rien à ajouter, mais lorsqu''il n''y a plus rien à retirer.', 'Antoine de Saint-Exupéry', 'mindset', 'Saint-Exupéry y parle de la conception des avions : la beauté d''une machine vient de tout ce qu''on a fini par lui retirer.', 'Terre des hommes', 1939),
  ('q-0707', 'On ne subit pas l''avenir, on le fait.', 'Georges Bernanos', 'mindset', null, null, null),
  ('q-0709', 'Le pessimiste se plaint du vent, l''optimiste espère qu''il va changer, le réaliste ajuste ses voiles.', 'William Arthur Ward', 'mindset', null, null, null),
  ('q-0710', 'Le doute est le commencement de la sagesse.', 'Aristote', 'mindset', null, null, null),
  ('q-0711', 'Nous sommes ce que nous faisons de manière répétée. L''excellence n''est donc pas un acte mais une habitude.', 'Will Durant', 'mindset', 'Souvent attribuée à Aristote : c''est en réalité le résumé qu''en fait Will Durant dans son ouvrage de vulgarisation. L''attribution ici est la bonne.', 'Histoire de la philosophie', 1926),
  ('q-0712', 'Tout le monde savait que c''était impossible. Il est venu un imbécile qui ne le savait pas et qui l''a fait.', 'Marcel Pagnol', 'mindset', null, null, null)
on conflict (id) do update set
  text = excluded.text,
  author = excluded.author,
  category = excluded.category,
  context = excluded.context,
  source = excluded.source,
  year = excluded.year,
  updated_at = now();

commit;
